// type: ["id", "Family", "Rarity", "DefaultSkin", "Size"]
export const pets = {
  605: ['Axolotl', 'Exotic', 'Common', 'Axolotl Pet Skin', '60'],
  1899: ['Cockatoo', 'Avian', 'Rare', 'Cockatoo Pet Skin', '80'],
  2222: ['Killer Bee Queen', 'Insect', 'Divine', 'Killer Bee Queen Skin', '80'],
  2381: ['Pigboot', 'Farm', 'Rare', 'Pigboot Pet Skin', '80'],
  3011: ['Platypus', 'Aquatic', 'Rare', 'Platypus Pet Skin', '80'],
  3014: ['Walrus', 'Aquatic', 'Rare', 'Walrus Pet Skin', '80'],
  3514: ['Blue Jay', 'Avian', 'Common', 'Blue Jay Pet Skin', '60'],
  3517: ['Vulture', 'Avian', 'Rare', 'Vulture Pet Skin', '80'],
  3596: ['Seal', 'Aquatic', 'Common', 'Seal Pet Skin', '60'],
  3659: ['Kiwi', 'Exotic', 'Common', 'Kiwi Pet Skin', '60'],
  3685: ['Zebra Spider', 'Insect', 'Rare', 'Zebra Spider Pet Skin', '80'],
  3688: ['Violet Larva', 'Insect', 'Common', 'Violet Larva Pet Skin', '60'],
  4068: ['Studious Frostwyrm', 'Reptile', 'Divine', 'Studious Frostwyrm Pet Skin', '80'],
  4071: [
    'Snowball Rolling Knight Yellow',
    'Humanoid',
    'Divine',
    'Snowball Rolling Knight Yellow Pet Skin',
    '80'
  ],
  4090: ['Blue Butterfly', 'Insect', 'Rare', 'Blue Butterfly Pet Skin', '80'],
  4093: ['Pink Butterfly', 'Insect', 'Rare', 'Pink Butterfly Pet Skin', '80'],
  5882: ['Verdant Larva', 'Insect', 'Common', 'Verdant Larva Pet Skin', '60'],
  5885: ['Ladybug', 'Insect', 'Rare', 'Ladybug Pet Skin', '80'],
  6053: ['Autumn Hedgehog', 'Woodland', 'Rare', 'Autumn Hedgehog Skin', '80'],
  6056: ['Mini Ghost Ship', '? ? ? ?', 'Rare', 'Mini Ghost Ship Skin', '80'],
  6065: ['Mini Model Ship', '? ? ? ?', 'Rare', 'Mini Model Ship Skin', '80'],
  6068: ['Healbot', 'Automaton', 'Rare', 'Healbot Skin', '80'],
  6071: ['Sugar Skull', 'Spooky', 'Rare', 'Sugar Skull Skin', '80'],
  6074: ['Cow', 'Farm', 'Rare', 'Cow Pet Skin', '80'],
  6077: ['White Duck', 'Farm', 'Rare', 'White Duck Pet Skin', '80'],
  6080: ['Senor Skeleton', 'Spooky', 'Rare', 'Senor Skeleton Skin', '80'],
  6083: ['Flying Eyeball', 'Spooky', 'Rare', 'Flying Eyeball Skin', '60'],
  6086: ['Mini Cauldron', 'Spooky', 'Rare', 'Mini Cauldron Skin', '60'],
  6089: ["Doom's Steed", 'Spooky', 'Divine', "Doom's Steed Skin", '80'],
  6090: ['Little Tiger', 'Feline', 'Rare', 'Little Tiger Pet Skin', '80'],
  6093: ['Worm', 'Insect', 'Common', 'Worm Pet Skin', '60'],
  6098: ['Lichwyrm', 'Spooky', 'Divine', 'Lichwyrm Skin', '80'],
  6101: ['Cauldron', 'Spooky', 'Divine', 'Cauldron Skin', '80'],
  6378: ['Bear', 'Woodland', 'Rare', 'Bear Pet Skin', '80'],
  6381: ['Moose', 'Woodland', 'Rare', 'Moose Pet Skin', '80'],
  6580: ['Frilled Lizard', 'Reptile', 'Rare', 'Frilled Lizard Skin', '80'],
  6590: ['Fire Rooster', 'Farm', 'Rare', 'Fire Rooster Skin', '80'],
  6593: ['Rooster of Good Fortune', 'Farm', 'Divine', 'Rooster of Good Fortune Skin', '80'],
  6596: ['Mini Chinese Dragon', 'Reptile', 'Rare', 'Mini Chinese Dragon Skin', '80'],
  6599: ['Gingerbread Man', '? ? ? ?', 'Rare', 'Gingerbread Man Skin', '80'],
  6602: ['Mini Polaris', '? ? ? ?', 'Rare', 'Mini Polaris Skin', '80'],
  6605: ['Mini Paper Lantern', '? ? ? ?', 'Divine', 'Mini Paper Lantern Skin', '80'],
  6608: ['Paper Lantern', '? ? ? ?', 'Divine', 'Paper Lantern Skin', '80'],
  6611: ['Chinese Dragon', 'Reptile', 'Divine', 'Chinese Dragon Skin', '80'],
  6614: ['Desert Cobra', 'Reptile', 'Rare', 'Desert Cobra Skin', '80'],
  6704: ['Mini Medusa', 'Reptile', 'Rare', 'Mini Medusa Pet Skin', '80'],
  6707: ['Mini Djinn', 'Humanoid', 'Rare', 'Mini Djinn Pet Skin', '80'],
  6710: ['Mini Ghost God', 'Spooky', 'Rare', 'Mini Ghost God Pet Skin', '80'],
  6713: ['Mini Flying Brain', 'Spooky', 'Rare', 'Mini Flying Brain Pet Skin', '80'],
  6716: ['Mini Beholder', 'Spooky', 'Rare', 'Mini Beholder Pet Skin', '80'],
  6719: ['Mini Sprite God', '? ? ? ?', 'Rare', 'Mini Sprite God Pet Skin', '80'],
  6722: ['Mini Ent God', 'Woodland', 'Rare', 'Mini Ent God Pet Skin', '80'],
  6725: ['Mini Slime God', '? ? ? ?', 'Rare', 'Mini Slime God Pet Skin', '80'],
  6728: ['Mini White Demon', 'Spooky', 'Rare', 'Mini White Demon Pet Skin', '80'],
  8388: ['Pillbug', 'Insect', 'Rare', 'Pillbug Pet Skin', '80'],
  8592: ['Brown Bulldog', 'Canine', 'Rare', 'Brown Bulldog Pet Skin', '80'],
  8595: ['White Bulldog', 'Canine', 'Rare', 'White Bulldog Pet Skin', '80'],
  8598: ['Dingo', 'Canine', 'Rare', 'Dingo Pet Skin', '80'],
  8661: ['Red Parrot', 'Exotic', 'Rare', 'Red Parrot Pet Skin', '80'],
  8708: ['Cheetah', 'Feline', 'Rare', 'Cheetah Pet Skin', '80'],
  8711: ['Jaguar', 'Feline', 'Rare', 'Jaguar Pet Skin', '80'],
  9162: ['Floomp', 'Reptile', 'Divine', 'Floomp Skin', '80'],
  9165: ['Vermilion Dragon', 'Reptile', 'Divine', 'Vermilion Dragon Skin', '80'],
  9170: ['Golden Capricorn', 'Farm', 'Divine', 'Golden Capricorn Skin', '70'],
  9173: ['Golden Sagittarius', 'Humanoid', 'Divine', 'Golden Sagittarius Skin', '70'],
  9176: ['Golden Aquarius', 'Humanoid', 'Divine', 'Golden Aquarius Skin', '70'],
  9179: ['Capricorn', 'Farm', 'Divine', 'Capricorn Skin', '70'],
  9182: ['Sagittarius', 'Humanoid', 'Divine', 'Sagittarius Skin', '70'],
  9186: ['Aquarius', 'Humanoid', 'Divine', 'Aquarius Skin', '70'],
  9189: ['Bouncing Slime', '? ? ? ?', 'Rare', 'Bouncing Slime Skin', '80'],
  9192: ['Mini Pot Of Gold', '? ? ? ?', 'Rare', 'Mini Pot Of Gold Skin', '80'],
  9195: ["Leprechaun's Walking Hat", '? ? ? ?', 'Rare', "Leprechaun's Walking Hat Skin", '80'],
  9198: ['Rainbow Rocketeer', 'Humanoid', 'Divine', 'Rainbow Rocketeer Skin', '80'],
  9251: ['Tuxedo Bird', 'Avian', 'Rare', 'Tuxedo Bird Pet Skin', '80'],
  9254: ['Flamingo', 'Exotic', 'Divine', 'Flamingo Pet Skin', '80'],
  9257: ['Heron', 'Avian', 'Divine', 'Heron Pet Skin', '80'],
  9260: ['Angelic Drake', 'Reptile', 'Divine', 'Angelic Drake Pet Skin', '80'],
  9263: ['Demonic Drake', 'Reptile', 'Divine', 'Demonic Drake Pet Skin', '80'],
  9266: ['Fusion Golem', 'Automaton', 'Divine', 'Fusion Golem Pet Skin', '80'],
  9269: ['Vibrant Seadragon', 'Aquatic', 'Divine', 'Vibrant Seadragon Pet Skin', '80'],
  9272: ['Arthro-bot', 'Automaton', 'Rare', 'Arthro-bot Pet Skin', '80'],
  9275: ['Mini Biff', 'Farm', 'Rare', 'Mini Biff Pet Skin', '80'],
  9278: ['Newborn Chick', 'Farm', 'Rare', 'Newborn Chick Pet Skin', '80'],
  9281: ['Amazon', 'Exotic', 'Rare', 'Amazon Pet Skin', '80'],
  9284: ['Party Crow', 'Avian', 'Rare', 'Party Crow Pet Skin', '80'],
  9287: ['Honey-bot Ant', 'Automaton', 'Rare', 'Honey-bot Ant Pet Skin', '80'],
  9290: ['Fountain Child', 'Humanoid', 'Rare', 'Fountain Child Pet Skin', '80'],
  9293: ['Desert Scorpion', 'Insect', 'Divine', 'Desert Scorpion Pet Skin', '80'],
  9296: ['Giant Centipede', 'Insect', 'Divine', 'Giant Centipede Pet Skin', '80'],
  9299: ['Silver Sky Serpent', 'Reptile', 'Divine', 'Silver Sky Serpent Pet Skin', '80'],
  9304: ['Twilight Angler', 'Aquatic', 'Divine', 'Twilight Angler Pet Skin', '80'],
  9307: ['Abyss Goliath', 'Reptile', 'Divine', 'Abyss Goliath Pet Skin', '80'],
  9740: ['Little Fox', 'Canine', 'Rare', 'Little Fox Pet Skin', '80'],
  9743: ['Mini Beer God', 'Humanoid', 'Rare', 'Mini Beer God Pet Skin', '80'],
  9746: ['Titanium Rex', 'Automaton', 'Divine', 'Titanium Rex Pet Skin', '80'],
  9749: ['Red Panda', 'Exotic', 'Divine', 'Red Panda Pet Skin', '80'],
  9752: ['Gargantua', 'Reptile', 'Divine', 'Gargantua Pet Skin', '80'],
  10912: ['White Bounsheep', 'Farm', 'Rare', 'White Bounsheep Skin', '80'],
  10915: ['Grey Bounsheep', 'Farm', 'Rare', 'Grey Bounsheep Skin', '80'],
  10918: ['Brown Bounsheep', 'Farm', 'Rare', 'Brown Bounsheep Skin', '80'],
  10921: ["Bes' Artifact", '? ? ? ?', 'Rare', "Bes' Artifact Skin", '80'],
  10924: ["Geb's Artifact", '? ? ? ?', 'Rare', "Geb's Artifact Skin", '80'],
  10927: ["Nut's Artifact", '? ? ? ?', 'Rare', "Nut's Artifact Skin", '80'],
  14095: ['Skelly Penguin', 'Penguin', 'Rare', 'Skelly Penguin Pet Skin', '80'],
  14098: ['Reticulated Longuin', 'Penguin', 'Divine', 'Reticulated Longuin Pet Skin', '80'],
  14101: ['Transcendent Penguin', 'Penguin', 'Divine', 'Transcendent Penguin Pet Skin', '80'],
  14104: ['Aeronautical Penguin', 'Penguin', 'Divine', 'Aeronautical Penguin Pet Skin', '80'],
  15711: ['Good Mask Spirit', 'Exotic', 'Divine', 'Good Mask Spirit Pet Skin', '80'],
  15714: ['Evil Mask Spirit', 'Exotic', 'Divine', 'Evil Mask Spirit Pet Skin', '80'],
  19184: ['Mini Sphinx', '? ? ? ?', 'Rare', 'Mini Sphinx Skin', '80'],
  19185: ['Mini Crystal Steed', '? ? ? ?', 'Rare', 'Mini Crystal Steed Skin', '80'],
  19186: ['Carnivorous Plant', '? ? ? ?', 'Rare', 'Carnivorous Plant Skin', '80'],
  19187: ['Knight Companion', '? ? ? ?', 'Divine', 'Knight Companion Skin', '80'],
  19188: ['Mr Cactus Jr.', '? ? ? ?', 'Rare', 'Mr Cactus Jr. Skin', '80'],
  19189: ['Mr Cactus', '? ? ? ?', 'Divine', 'Mr Cactus Skin', '80'],
  19382: ['Mini Limon', '? ? ? ?', 'Rare', 'Mini Limon Skin', '80'],
  19461: ['Mini Stone Oryx', '? ? ? ?', 'Rare', 'Mini Stone Oryx Skin', '80'],
  19464: ['Mini Gigacorn', '? ? ? ?', 'Rare', 'Mini Gigacorn Skin', '80'],
  19467: ['Mini Creampuff', '? ? ? ?', 'Rare', 'Mini Creampuff Skin', '80'],
  19470: ['Mini Desire Troll', '? ? ? ?', 'Rare', 'Mini Desire Troll Skin', '80'],
  19473: ['Mini Rototo', '? ? ? ?', 'Rare', 'Mini Rototo Skin', '80'],
  19476: ['Mini Flying Stheno', 'Reptile', 'Rare', 'Mini Flying Stheno Skin', '80'],
  19479: ['Surfing Bro', 'Humanoid', 'Divine', 'Surfing Bro Skin', '80'],
  19502: ['Mini Ghost King', 'Spooky', 'Rare', 'Mini Ghost King Skin', '80'],
  19505: ['Robo Brain', 'Automaton', 'Rare', 'Robo Brain Skin', '80'],
  19508: ['Baby Orange Drake', 'Reptile', 'Rare', 'Baby Orange Drake Skin', '80'],
  19511: ['Baby Yellow Drake', 'Reptile', 'Rare', 'Baby Yellow Drake Skin', '80'],
  19514: ['Baby White Drake', 'Reptile', 'Rare', 'Baby White Drake Skin', '80'],
  19517: ['Baby Green Drake', 'Reptile', 'Rare', 'Baby Green Drake Skin', '80'],
  19520: ['Mini Leviathan', 'Reptile', 'Rare', 'Mini Leviathan Skin', '80'],
  19523: ['Baby Blue Drake', 'Reptile', 'Rare', 'Baby Blue Drake Skin', '80'],
  19526: ['Baby Purple Drake', 'Reptile', 'Rare', 'Baby Purple Drake Skin', '80'],
  19533: ['Pet HP Pot', '? ? ? ?', 'Rare', 'Pet HP Pot Skin', '80'],
  19536: ['Pet MP Pot', '? ? ? ?', 'Rare', 'Pet MP Pot Skin', '80'],
  19595: ['Crowned Penguin', 'Penguin', 'Rare', 'Crowned Penguin Skin', '80'],
  19598: ['Mini Void Entity', 'Spooky', 'Rare', 'Mini Void Entity Skin', '80'],
  19601: ['Hoverbot', 'Automaton', 'Rare', 'Hoverbot Skin', '80'],
  19604: ['Zombie Dog', 'Canine', 'Rare', 'Zombie Dog Skin', '80'],
  19607: ['Green Whale', 'Aquatic', 'Divine', 'Green Whale Skin', '80'],
  19610: ["Pumpking's Head", 'Spooky', 'Divine', "Pumpking's Head Skin", '80'],
  19625: ['Manticore', 'Feline', 'Divine', 'Manticore Skin', '80'],
  19628: ['Flying Pig', 'Farm', 'Divine', 'Flying Pig Skin', '80'],
  19631: ['Double Viper', 'Reptile', 'Divine', 'Double Viper Skin', '80'],
  19634: ['Black Hellhound', 'Canine', 'Divine', 'Black Hellhound Skin', '80'],
  19637: ['Deerigator', 'Reptile', 'Divine', 'Deerigator Skin', '80'],
  19640: ['Moon Bunny', 'Farm', 'Rare', 'Moon Bunny Skin', '80'],
  19643: ['Hungry Pumpkin', 'Spooky', 'Rare', 'Hungry Pumpkin Skin', '80'],
  19646: ['Evil Ghost', 'Spooky', 'Rare', 'Evil Ghost Skin', '80'],
  19649: ['Spooky Boi', 'Spooky', 'Rare', 'Spooky Boi Skin', '80'],
  19652: ['Walking Grave', 'Spooky', 'Rare', 'Walking Grave Skin', '80'],
  21640: ['Enlightened Bookwyrm', 'Reptile', 'Divine', 'Enlightened Bookwyrm Pet Skin', '80'],
  22583: ['Bogged Panda', 'Exotic', 'Divine', 'Bogged Panda Pet Skin', '80'],
  23308: ['Mini Lord', '? ? ? ?', 'Rare', 'Mini Lord Pet Skin', '80'],
  23311: ['Mini Tornado', '? ? ? ?', 'Common', 'Mini Tornado Pet Skin', '60'],
  23314: ['Wooden Burrito', '? ? ? ?', 'Rare', 'Wooden Burrito Pet Skin', '80'],
  23317: ['Mini Nikao', '? ? ? ?', 'Rare', 'Mini Nikao Pet Skin', '80'],
  23320: ["Lil' Davy", '? ? ? ?', 'Rare', "Lil' Davy Pet Skin", '80'],
  23323: ['Maneki-neko', 'Feline', 'Rare', 'Maneki-neko Pet Skin', '80'],
  24602: ['King Skin of the Toys', '? ? ? ?', 'Divine', 'King Skin of the Toys Skin', '70'],
  24605: ['Festive Slurp', 'Aquatic', 'Rare', 'Festive Slurp Skin', '70'],
  24609: ['Holiday Penguin', 'Penguin', 'Rare', 'Holiday Penguin Skin', '80'],
  24612: ['Young Elk', 'Woodland', 'Divine', 'Young Elk Skin', '60'],
  24615: ['Krampus', 'Spooky', 'Divine', 'Krampus Skin', '70'],
  24648: ['Egg Monster', 'Spooky', 'Rare', 'Egg Monster Skin', '60'],
  24651: ['Peacock', 'Avian', 'Divine', 'Peacock Skin', '60'],
  24654: ['Tricycle Bot', 'Automaton', 'Rare', 'Tricycle Bot Skin', '90'],
  24657: ['Mini Candy Gnome', 'Humanoid', 'Rare', 'Mini Candy Gnome Skin', '80'],
  24660: ["Lil' Mummy", 'Spooky', 'Common', "Lil' Mummy Skin", '60'],
  24663: ['Parasaurolophus', 'Reptile', 'Divine', 'Parasaurolophus Skin', '70'],
  24666: ['Lambeosaurus', 'Reptile', 'Divine', 'Lambeosaurus Skin', '70'],
  24689: ['Guiding Spirit', '? ? ? ?', 'Rare', 'Guiding Spirit Skin', '60'],
  24723: ['Red Heart', '? ? ? ?', 'Rare', 'Red Heart Skin', '40'],
  24726: ['Pink Heart', '? ? ? ?', 'Rare', 'Pink Heart Skin', '40'],
  24729: ['Mini Pegasus', 'Farm', 'Rare', 'Mini Pegasus Skin', '80'],
  24732: ['Prince Frog', 'Aquatic', 'Rare', 'Prince Frog Skin', '80'],
  24735: ['Lovebird', 'Avian', 'Rare', 'Lovebird Skin', '80'],
  24832: ['Marid', 'Humanoid', 'Divine', 'Marid Skin', '80'],
  24835: ['Sir Bagston', '? ? ? ?', 'Divine', 'Bagston Skin', '80'],
  24838: ['Goldy', '? ? ? ?', 'Divine', 'Goldy Skin', '80'],
  24841: ['Jaco', 'Spooky', 'Divine', 'Jaco Skin', '80'],
  25090: ['Rat', 'Woodland', 'Common', 'Rat Skin', '60'],
  25093: ['Goldfish', 'Aquatic', 'Rare', 'Goldfish Skin', '80'],
  25096: ['Giant Monarch', 'Insect', 'Divine', 'Giant Monarch Skin', '60'],
  25099: ['Zodiac Dog', 'Canine', 'Divine', 'Zodiac Dog Skin', '80'],
  25608: ['World Turtles', 'Reptile', 'Divine', 'World Turtles Pet Skin', '80'],
  28812: ['Morpho', 'Insect', 'Rare', 'Morpho Pet Skin', '80'],
  29252: ['Swamped Panda', 'Exotic', 'Divine', 'Swamped Panda Pet Skin', '80'],
  29344: ['Living Tree', 'Woodland', 'Rare', 'Living Tree Pet Skin', '80'],
  29347: ['Chinchilla', 'Exotic', 'Rare', 'Chinchilla Pet Skin', '80'],
  29350: ['Golden Chess Piece', '? ? ? ?', 'Rare', 'Golden Chess Piece Pet Skin', '80'],
  29353: ['Sprout Slime', '? ? ? ?', 'Divine', 'Sprout Slime Pet Skin', '80'],
  30058: ['Ivory Narwhal', 'Aquatic', 'Divine', 'Ivory Narwhal Pet Skin', '80'],
  30061: ['Armored Orc', 'Humanoid', 'Divine', 'Armored Orc Pet Skin', '80'],
  30064: ['Enchanted Broom', '? ? ? ?', 'Divine', 'Enchanted Broom Pet Skin', '80'],
  30067: ['Hollow Wendigo', 'Spooky', 'Divine', 'Hollow Wendigo Pet Skin', '80'],
  30070: ['Tree Sparrow', 'Avian', 'Common', 'Tree Sparrow Pet Skin', '60'],
  30073: ['White Eyed', 'Avian', 'Common', 'White Eyed Pet Skin', '60'],
  30076: ['Polar Bear', 'Exotic', 'Divine', 'Polar Bear Pet Skin', '80'],
  30079: ['Snow Monster', 'Spooky', 'Divine', 'Snow Monster Pet Skin', '80'],
  30082: ['Longtailed Tit', 'Avian', 'Common', 'Longtailed Tit Pet Skin', '60'],
  30085: ['Searing Soul', '? ? ? ?', 'Divine', 'Searing Soul Pet Skin', '80'],
  30088: ['Zodiac Pig', 'Farm', 'Divine', 'Zodiac Pig Pet Skin', '80'],
  30102: ['Swan', 'Farm', 'Divine', 'Swan Pet Skin', '80'],
  30105: ['Green Hat Bunny', 'Farm', 'Rare', 'Green Hat Bunny Pet Skin', '80'],
  30108: ['Cultured Bookwyrm', 'Reptile', 'Divine', 'Cultured Bookwyrm Pet Skin', '80'],
  30111: ['Mini Whale', 'Aquatic', 'Rare', 'Mini Whale Pet Skin', '80'],
  30114: ['Champion Spirit', 'Spooky', 'Divine', 'Champion Spirit Pet Skin', '80'],
  30117: ['Vicious Phantom', 'Spooky', 'Divine', 'Vicious Phantom Pet Skin', '80'],
  30120: ['Toaster', '? ? ? ?', 'Divine', 'Toaster Pet Skin', '80'],
  30123: ['Warrior Duck', 'Humanoid', 'Divine', 'Warrior Duck Pet Skin', '80'],
  30126: ['Infested Bagston', '? ? ? ?', 'Divine', 'Infested Bagston Pet Skin', '80'],
  30129: ['Crystal Cobra', 'Reptile', 'Divine', 'Crystal Cobra Pet Skin', '80'],
  30132: ['Possessed Lantern', 'Spooky', 'Divine', 'Possessed Lantern Pet Skin', '80'],
  30135: ['Malogian Saucer', 'Automaton', 'Divine', 'Malogian Saucer Pet Skin', '80'],
  30138: ['Untarian Saucer', 'Automaton', 'Divine', 'Untarian Saucer Pet Skin', '80'],
  30141: ['Foraxian Saucer', 'Automaton', 'Divine', 'Foraxian Saucer Pet Skin', '80'],
  30144: ['Katalonian Saucer', 'Automaton', 'Divine', 'Katalonian Saucer Pet Skin', '80'],
  30147: ['Chill Chickey', 'Avian', 'Divine', 'Chill Chickey Pet Skin', '80'],
  30150: ['Sir Wumple', 'Humanoid', 'Rare', 'Sir Wumple Pet Skin', '80'],
  30153: ['Shiba Inu', 'Canine', 'Rare', 'Shiba Inu Pet Skin', '80'],
  30156: ['Blue Turtle Shell', '? ? ? ?', 'Divine', 'Blue Turtle Shell Pet Skin', '80'],
  30159: ['Green Turtle Shell', '? ? ? ?', 'Rare', 'Green Turtle Shell Pet Skin', '80'],
  30162: ['Red Turtle Shell', '? ? ? ?', 'Rare', 'Red Turtle Shell Pet Skin', '80'],
  30165: ['Skelephant', 'Spooky', 'Divine', 'Skelephant Pet Skin', '80'],
  30168: ['Phantom Tea Set', '? ? ? ?', 'Divine', 'Phantom Tea Set Pet Skin', '80'],
  30171: ["Fool's Penguin", 'Penguin', 'Divine', "Fool's Penguin Pet Skin", '80'],
  30174: ['Phantom Ghost', 'Humanoid', 'Divine', 'Phantom Ghost Pet Skin', '80'],
  30177: ['UFO Bot', 'Automaton', 'Rare', 'UFO Bot Pet Skin', '80'],
  30180: ['Cyberpenguin', 'Penguin', 'Divine', 'Cyberpenguin Pet Skin', '80'],
  30183: ['Blue Flaming Pumpkin', 'Spooky', 'Divine', 'Blue Flaming Pumpkin Pet Skin', '80'],
  30186: ['Orange Flaming Pumpkin', 'Spooky', 'Divine', 'Orange Flaming Pumpkin Pet Skin', '80'],
  30189: ['Flying Penguin', 'Penguin', 'Rare', 'Flying Penguin Pet Skin', '80'],
  30192: ['Fire Spirit', '? ? ? ?', 'Divine', 'Fire Spirit Pet Skin', '80'],
  30195: ['Earth Spirit', '? ? ? ?', 'Divine', 'Earth Spirit Pet Skin', '80'],
  30198: ['Water Spirit', '? ? ? ?', 'Divine', 'Water Spirit Pet Skin', '80'],
  30201: ["Santa's Penguin", 'Penguin', 'Divine', "Santa's Penguin Pet Skin", '80'],
  30207: ['Auroral Sprite God', '? ? ? ?', 'Divine', 'Auroral Sprite God Pet Skin', '80'],
  30210: ['Cursed Blade', '? ? ? ?', 'Divine', 'Cursed Blade Pet Skin', '80'],
  30213: ['Mini Marble Colossus', '? ? ? ?', 'Rare', 'Mini Marble Colossus Pet Skin', '80'],
  30216: ['Majestic Moose', 'Woodland', 'Divine', 'Majestic Moose Pet Skin', '80'],
  30219: ['Winter Guide', 'Humanoid', 'Divine', 'Winter Guide Pet Skin', '80'],
  30222: ['Air Spirit', '? ? ? ?', 'Divine', 'Air Spirit Pet Skin', '80'],
  30225: ['Zodiac Rat', 'Farm', 'Divine', 'Zodiac Rat Pet Skin', '80'],
  30228: ['Blessed Blade', '? ? ? ?', 'Divine', 'Blessed Blade Pet Skin', '80'],
  30231: ['Suntanned Snowman', '? ? ? ?', 'Rare', 'Suntanned Snowman Pet Skin', '80'],
  30234: ['Pet Wardrobe', 'Spooky', 'Divine', 'Pet Wardrobe Pet Skin', '80'],
  30237: ['Compact Enforcer', 'Automaton', 'Divine', 'Compact Enforcer Pet Skin', '80'],
  30240: ['Ferret', 'Woodland', 'Divine', 'Ferret Pet Skin', '80'],
  30243: ['Grub', '? ? ? ?', 'Divine', 'Grub Pet Skin', '80'],
  30246: ['Ascended Guardian', 'Penguin', 'Divine', 'Ascended Guardian Pet Skin', '80'],
  30249: ['Music Box', '? ? ? ?', 'Divine', 'Music Box Pet Skin', '80'],
  30252: ['Void Hound', 'Canine', 'Divine', 'Void Hound Pet Skin', '80'],
  30255: ['Autumn Guide', 'Humanoid', 'Divine', 'Autumn Guide Pet Skin', '80'],
  30258: ['Time Traveling Phonebox', '? ? ? ?', 'Divine', 'Time Traveling Phonebox Pet Skin', '80'],
  30261: ['Summer Guide', 'Humanoid', 'Divine', 'Summer Guide Pet Skin', '80'],
  30264: ['Old Nexus Orc', 'Humanoid', 'Divine', 'Old Nexus Orc Pet Skin', '80'],
  30267: ['TV Buddy', '? ? ? ?', 'Rare', 'TV Buddy Pet Skin', '80'],
  30270: ['Demon Cat', 'Feline', 'Rare', 'Demon Cat Pet Skin', '80'],
  30273: ['House Cat', 'Feline', 'Rare', 'House Cat Pet Skin', '80'],
  30276: ['Husky', 'Canine', 'Rare', 'Husky Pet Skin', '80'],
  30279: ['Floating Eye Bot', 'Automaton', 'Divine', 'Floating Eye Bot Pet Skin', '80'],
  30282: ['Enchanted Sea Turtle', 'Aquatic', 'Divine', 'Enchanted Sea Turtle Pet Skin', '80'],
  30285: ['Giant Worm', 'Insect', 'Divine', 'Giant Worm Pet Skin', '80'],
  30288: ['Bulldozer Penguin', 'Penguin', 'Divine', 'Bulldozer Penguin Pet Skin', '80'],
  30291: ['Mobile Crane Penguin', 'Penguin', 'Divine', 'Mobile Crane Penguin Pet Skin', '80'],
  30294: ['Excavator Penguin', 'Penguin', 'Divine', 'Excavator Penguin Pet Skin', '80'],
  30297: ['Road Roller Penguin', 'Penguin', 'Divine', 'Road Roller Penguin Pet Skin', '80'],
  30300: [
    'Traffic Controller Penguin',
    'Penguin',
    'Rare',
    'Traffic Controller Penguin Pet Skin',
    '80'
  ],
  30303: ['Hungry Toolbox', '? ? ? ?', 'Rare', 'Hungry Toolbox Pet Skin', '80'],
  30306: ['Janus the Fategazer', '? ? ? ?', 'Divine', 'Janus the Fategazer Pet Skin', '80'],
  30309: ['Mini Guill', 'Humanoid', 'Rare', 'Mini Guill Pet Skin', '80'],
  30312: ['Nexus Sheep', 'Farm', 'Rare', 'Nexus Sheep Pet Skin', '80'],
  30315: ['Stone Brothers', 'Humanoid', 'Divine', 'Stone Brothers Pet Skin', '80'],
  30318: ['Oryx the Exalted', '? ? ? ?', 'Divine', 'Oryx the Exalted Pet Skin', '80'],
  30321: ['Sapling Buddy', 'Woodland', 'Rare', 'Sapling Buddy Pet Skin', '80'],
  30324: ['Scallywag Slurp', 'Aquatic', 'Rare', 'Scallywag Slurp Pet Skin', '80'],
  30327: ['Baby Basilisk', 'Reptile', 'Rare', 'Baby Basilisk Pet Skin', '80'],
  30330: ['Horned Wyrm', 'Reptile', 'Divine', 'Horned Wyrm Pet Skin', '80'],
  30333: ['Possessed Staff', '? ? ? ?', 'Divine', 'Possessed Staff Pet Skin', '80'],
  30336: ['Eggshell Spider', 'Insect', 'Rare', 'Eggshell Spider Pet Skin', '80'],
  30339: ['Blizzard', 'Feline', 'Divine', 'Blizzard Pet Skin', '80'],
  30342: ['Fiery Phylactery', 'Spooky', 'Divine', 'Fiery Phylactery Pet Skin', '80'],
  30345: ['Giant Zombie Feet', 'Spooky', 'Divine', 'Giant Zombie Feet Pet Skin', '80'],
  30348: ['Skeleton Drake', 'Reptile', 'Divine', 'Skeleton Drake Pet Skin', '80'],
  30351: ['Zombie Drake', 'Reptile', 'Divine', 'Zombie Drake Pet Skin', '80'],
  30354: ['Witch Hat Rat', 'Spooky', 'Divine', 'Witch Hat Rat Pet Skin', '80'],
  30357: ['Spectral Skeledragon', 'Spooky', 'Divine', 'Spectral Skeledragon Pet Skin', '80'],
  30360: ['King Rarthur', 'Woodland', 'Divine', 'King Rarthur Pet Skin', '80'],
  30363: ['Red-Nosed Friend', 'Woodland', 'Rare', 'Red-Nosed Friend Pet Skin', '80'],
  30366: ['Mouse Prince', 'Woodland', 'Rare', 'Mouse Prince Pet Skin', '80'],
  30369: ['Aerodynamical Penguin', 'Penguin', 'Divine', 'Aerodynamical Penguin Pet Skin', '80'],
  30372: ['Big Pingus', 'Penguin', 'Divine', 'Big Pingus Pet Skin', '80'],
  30375: ['Zodiac Ox', 'Farm', 'Divine', 'Zodiac Ox Pet Skin', '80'],
  30378: ["Mini 'Odonna", '? ? ? ?', 'Rare', "Mini 'Odonna Pet Skin", '80'],
  30381: ["Lil' Forest Harpy", 'Humanoid', 'Rare', "Lil' Forest Harpy Pet Skin", '80'],
  30384: ['Valentine Cupcake', '? ? ? ?', 'Divine', 'Valentine Cupcake Pet Skin', '80'],
  30387: ['Lovey Teddy', '? ? ? ?', 'Divine', 'Lovey Teddy Pet Skin', '80'],
  30390: ['Android Companion', 'Automaton', 'Divine', 'Android Companion Pet Skin', '80'],
  30393: ['Nightray Pegasus', 'Farm', 'Divine', 'Nightray Pegasus Pet Skin', '80'],
  30396: ['Glorious Pegasus', 'Farm', 'Divine', 'Glorious Pegasus Pet Skin', '80'],
  30399: ['Forest Harpy', 'Humanoid', 'Divine', 'Forest Harpy Pet Skin', '80'],
  30402: ['Helicopter Penguin', 'Penguin', 'Divine', 'Helicopter Penguin Pet Skin', '80'],
  30405: ['Infernal Archdragon', 'Reptile', 'Divine', 'Infernal Archdragon Pet Skin', '80'],
  30408: ['Sakura Deer', 'Woodland', 'Divine', 'Sakura Deer Pet Skin', '80'],
  30411: ['Lucky Fourleaf', 'Woodland', 'Divine', 'Lucky Fourleaf Pet Skin', '80'],
  30414: ['Golden Lucky Fourleaf', 'Woodland', 'Divine', 'Golden Lucky Fourleaf Pet Skin', '80'],
  30417: ['Chocolate Bunny', 'Farm', 'Rare', 'Chocolate Bunny Pet Skin', '80'],
  30420: ['Battlebot MK1', 'Automaton', 'Divine', 'Battlebot MK1 Pet Skin', '80'],
  30423: ['Mystery Rare Pet', '? ? ? ?', 'Rare', 'Mystery Rare Pet Skin', '80'],
  30426: ['Mystery Epic Pet', '? ? ? ?', 'Rare', 'Mystery Epic Pet Skin', '80'],
  30429: ['Mystery Legendary Pet', '? ? ? ?', 'Rare', 'Mystery Legendary Pet Skin', '80'],
  30432: ['Easter Island Head', '? ? ? ?', 'Divine', 'Easter Island Head Pet Skin', '80'],
  30435: ['Gazelle', 'Exotic', 'Divine', 'Gazelle Pet Skin', '80'],
  30438: ['Crystal Pony', '? ? ? ?', 'Rare', 'Crystal Pony Pet Skin', '80'],
  30441: [
    'Son of the Son of Arachna',
    'Insect',
    'Rare',
    'Son of the Son of Arachna Pet Skin',
    '80'
  ],
  30444: ['Calamity Crab', 'Insect', 'Rare', 'Calamity Crab Pet Skin', '80'],
  30448: ['Bananalien', '? ? ? ?', 'Divine', 'Bananalien Pet Skin', '80'],
  30451: ['Egg-bot', 'Automaton', 'Divine', 'Egg-bot Pet Skin', '80'],
  30454: ['Malus?', 'Humanoid', 'Divine', 'Malus? Pet Skin', '80'],
  30457: ['Biard', 'Avian', 'Divine', 'Biard Pet Skin', '80'],
  30460: ['Oryx the Baby God', 'Humanoid', 'Rare', 'Oryx the Baby God Pet Skin', '80'],
  30463: ['Sol the Energy Drink', '? ? ? ?', 'Divine', 'Sol the Energy Drink Pet Skin', '80'],
  30466: ['Skulking Skull King', 'Spooky', 'Divine', 'Skulking Skull King Pet Skin', '80'],
  30469: ['Octopus', 'Aquatic', 'Divine', 'Octopus Pet Skin', '80'],
  30472: ['Snail of the Juggernaut', 'Aquatic', 'Rare', 'Snail of the Juggernaut Pet Skin', '80'],
  30475: ['Fallen Protector', 'Humanoid', 'Divine', 'Fallen Protector Pet Skin', '80'],
  30478: ['Redeemed Void Shade', 'Humanoid', 'Divine', 'Redeemed Void Shade Pet Skin', '80'],
  30481: ['Duality', '? ? ? ?', 'Divine', 'Duality Pet Skin', '80'],
  30484: ['Daeva Oryx', 'Humanoid', 'Divine', 'Daeva Oryx Pet Skin', '80'],
  30487: ['Seraphim', '? ? ? ?', 'Divine', 'Seraphim Pet Skin', '80'],
  30490: ['Voided Oryx', '? ? ? ?', 'Divine', 'Voided Oryx Pet Skin', '80'],
  30493: ['Corrupted Tinkerer', 'Humanoid', 'Rare', 'Corrupted Tinkerer Pet Skin', '80'],
  30496: ['Corrupted Login Seer', 'Humanoid', 'Rare', 'Corrupted Login Seer Pet Skin', '80'],
  30499: ["Lil' Ice Cream", '? ? ? ?', 'Rare', "Lil' Ice Cream Pet Skin", '80'],
  30502: ['Fizzy Drink', '? ? ? ?', 'Rare', 'Fizzy Drink Pet Skin', '80'],
  30505: ['Cured Tinkerer', 'Humanoid', 'Rare', 'Cured Tinkerer Pet Skin', '80'],
  30508: ['Cured Login Seer', 'Humanoid', 'Rare', 'Cured Login Seer Pet Skin', '80'],
  30511: ['Eye of the Void', 'Spooky', 'Rare', 'Eye of the Void Pet Skin', '80'],
  30514: ['Celestial Construct', 'Automaton', 'Rare', 'Celestial Construct Pet Skin', '80'],
  30517: ["Lil' Dark Ambrosia", '? ? ? ?', 'Rare', "Lil' Dark Ambrosia Pet Skin", '80'],
  30520: ['Corrupted Watering Can', '? ? ? ?', 'Divine', 'Corrupted Watering Can Pet Skin', '80'],
  30523: [
    'Corrupted Penguin Explorer',
    'Penguin',
    'Divine',
    'Corrupted Penguin Explorer Pet Skin',
    '80'
  ],
  30526: ['Void Cleanser Penguin', 'Penguin', 'Divine', 'Void Cleanser Penguin Pet Skin', '80'],
  30529: ['Sentinel Watchdog', 'Canine', 'Divine', 'Sentinel Watchdog Pet Skin', '80'],
  30532: ['Shadow Stormbird', 'Avian', 'Divine', 'Shadow Stormbird Pet Skin', '80'],
  30535: ['Royal Void Cat', 'Feline', 'Divine', 'Royal Void Cat Pet Skin', '80'],
  30538: ["Lil' Keyper", 'Humanoid', 'Rare', "Lil' Keyper Pet Skin", '80'],
  30541: ['Angelic Blossom', '? ? ? ?', 'Rare', 'Angelic Blossom Pet Skin', '80'],
  30544: ['Nurse Wheelie', 'Automaton', 'Divine', 'Nurse Wheelie Pet Skin', '80'],
  30547: ['Sphenisciform Entity', 'Penguin', 'Divine', 'Sphenisciform Entity Pet Skin', '80'],
  30550: ['Cherubic Penguin', 'Penguin', 'Divine', 'Cherubic Penguin Pet Skin', '80'],
  30553: ['Graylien', '? ? ? ?', 'Divine', 'Graylien Pet Skin', '80'],
  30556: ['Carnage Cat', 'Feline', 'Rare', 'Carnage Cat Pet Skin', '80'],
  30559: ["Lil' Backpack", '? ? ? ?', 'Divine', "Lil' Backpack Pet Skin", '80'],
  30562: ['Clipboard', '? ? ? ?', 'Divine', 'Clipboard Pet Skin', '80'],
  30565: ['Floating Beer', '? ? ? ?', 'Divine', 'Floating Beer Pet Skin', '80'],
  30568: ['Garlic Buddy', '? ? ? ?', 'Divine', 'Garlic Buddy Pet Skin', '80'],
  30570: ['Golden Pet Rock', '? ? ? ?', 'Divine', 'Golden Pet Rock Skin', '80'],
  30577: ['Spectral Bat', 'Spooky', 'Divine', 'Spectral Bat Pet Skin', '80'],
  30580: ['Ghastly Penguin', 'Penguin', 'Divine', 'Ghastly Penguin Pet Skin', '80'],
  30583: ['Cursed Portrait', 'Spooky', 'Divine', 'Cursed Portrait Pet Skin', '80'],
  30586: ['Bloodthirsty Penguin', 'Penguin', 'Divine', 'Bloodthirsty Penguin Pet Skin', '80'],
  30610: ['Eldritch Clown', 'Spooky', 'Divine', 'Eldritch Clown Pet Skin', '80'],
  30613: ['Campfire', '? ? ? ?', 'Divine', 'Campfire Pet Skin', '80'],
  30976: ['George the Turkey', 'Farm', 'Divine', 'George the Turkey Pet Skin', '80'],
  30979: ['Snowplow Penguin', 'Penguin', 'Divine', 'Snowplow Penguin Pet Skin', '80'],
  30982: ['Movement Detector Doll', 'Automaton', 'Divine', 'Movement Detector Doll Pet Skin', '80'],
  30985: ['Festive Sprite', '? ? ? ?', 'Rare', 'Festive Sprite Pet Skin', '80'],
  30988: ['Oryxmas Shiba', 'Canine', 'Rare', 'Oryxmas Shiba Pet Skin', '80'],
  30991: ['Gift-wrapped Box', 'Feline', 'Divine', 'Gift-wrapped Box Pet Skin', '80'],
  30994: ['Demon Mistress', 'Humanoid', 'Divine', 'Demon Mistress Pet Skin', '80'],
  30997: ['Ice Skating Penguin', 'Penguin', 'Divine', 'Ice Skating Penguin Pet Skin', '80'],
  31000: ['Oryxmas Tanuki', 'Canine', 'Rare', 'Oryxmas Tanuki Pet Skin', '80'],
  31003: ['Yau Gok', '? ? ? ?', 'Rare', 'Yau Gok Pet Skin', '80'],
  31006: ['Bouncy Companion', '? ? ? ?', 'Rare', 'Bouncy Companion Pet Skin', '80'],
  31009: ['Leprechaun Penguin', 'Penguin', 'Rare', 'Leprechaun Penguin Pet Skin', '80'],
  31012: ['Young Water Elemental', '? ? ? ?', 'Rare', 'Young Water Elemental Pet Skin', '80'],
  31015: ['Young Earth Elemental', '? ? ? ?', 'Rare', 'Young Earth Elemental Pet Skin', '80'],
  31018: ['Playful Bunny', 'Humanoid', 'Rare', 'Playful Bunny Pet Skin', '80'],
  31021: ['Young Fire Elemental', '? ? ? ?', 'Rare', 'Young Fire Elemental Pet Skin', '80'],
  31024: ['Young Air Elemental', '? ? ? ?', 'Rare', 'Young Air Elemental Pet Skin', '80'],
  31027: ['Perception of Guill', 'Humanoid', 'Rare', 'Perception of Guill Pet Skin', '80'],
  31030: ['Elemental Beast', 'Canine', 'Divine', 'Elemental Beast Pet Skin', '80'],
  31033: ["Lil' Deep Sea Diva", 'Aquatic', 'Rare', "Lil' Deep Sea Diva Pet Skin", '80'],
  31036: ["Lil' Mister Backstage", 'Humanoid', 'Rare', "Lil' Mister Backstage Pet Skin", '80'],
  31039: ["Lil' Rad Raver", 'Aquatic', 'Rare', "Lil' Rad Raver Pet Skin", '80'],
  31042: ["Lil' Thunderbringer", 'Humanoid', 'Rare', "Lil' Thunderbringer Pet Skin", '80'],
  31057: [
    'Deep Sea Diva Action Figure',
    'Aquatic',
    'Divine',
    'Deep Sea Diva Action Figure Pet Skin',
    '80'
  ],
  31060: [
    'Mister Backstage Action Figure',
    'Humanoid',
    'Divine',
    'Mister Backstage Action Figure Pet Skin',
    '80'
  ],
  31063: ['Rad Raver Action Figure', 'Aquatic', 'Divine', 'Rad Raver Action Figure Pet Skin', '80'],
  31066: [
    'The Thunderbringer Action Figure',
    'Humanoid',
    'Divine',
    'The Thunderbringer Action Figure Pet Skin',
    '80'
  ],
  31069: ['White Husky', 'Canine', 'Divine', 'White Husky Pet Skin', '80'],
  31072: ['Arctic Fox', 'Canine', 'Divine', 'Arctic Fox Pet Skin', '80'],
  31075: ['Penguin Gunslinger', 'Penguin', 'Divine', 'Penguin Gunslinger Pet Skin', '80'],
  31078: ['Dimensional Wanderer', 'Humanoid', 'Divine', 'Dimensional Wanderer Pet Skin', '80'],
  31081: ['Syndicate Hellhound', 'Canine', 'Divine', 'Syndicate Hellhound Pet Skin', '80'],
  31084: ['Voodoo Doll', 'Spooky', 'Divine', 'Voodoo Doll Pet Skin', '80'],
  31087: ['Voodoo Bat', 'Spooky', 'Divine', 'Voodoo Bat Pet Skin', '80'],
  31090: ['Chibi Bridge Sentinel', 'Humanoid', 'Divine', 'Chibi Bridge Sentinel Pet Skin', '80'],
  31093: [
    'Chibi Twilight Archmage',
    'Humanoid',
    'Divine',
    'Chibi Twilight Archmage Pet Skin',
    '80'
  ],
  31100: ['Chibi Forgotten King', 'Humanoid', 'Divine', 'Chibi Forgotten King Pet Skin', '80'],
  31103: ['Chibi Oryx', 'Humanoid', 'Divine', 'Chibi Oryx Pet Skin', '80'],
  31108: [
    'Chibi Heart of the Wetlands',
    'Woodland',
    'Divine',
    'Chibi Heart of the Wetlands Pet Skin',
    '80'
  ],
  31115: ['Mechanical Dog', 'Canine', 'Divine', 'Mechanical Dog Pet Skin', '80'],
  31118: ['Steampunk Cat', 'Feline', 'Divine', 'Steampunk Cat Pet Skin', '80'],
  32514: ['Autumn Ent', 'Woodland', 'Divine', 'Autumn Ent Pet Skin', '80'],
  32517: ['Black Cat', 'Feline', 'Common', 'Black Cat Skin', '60'],
  32518: ['Grey Cat', 'Feline', 'Common', 'Grey Cat Skin', '60'],
  32519: ['Orange Cat', 'Feline', 'Common', 'Orange Cat Skin', '60'],
  32520: ['Tan Cat', 'Feline', 'Common', 'Tan Cat Skin', '60'],
  32521: ['Yellow Cat', 'Feline', 'Common', 'Yellow Cat Skin', '60'],
  32522: ['White Cat', 'Feline', 'Common', 'White Cat Skin', '60'],
  32523: ['Brown Pup', 'Canine', 'Common', 'Brown Pup Skin', '60'],
  32524: ['Grey Pup', 'Canine', 'Common', 'Grey Pup Skin', '60'],
  32525: ['Golden Pup', 'Canine', 'Common', 'Golden Pup Skin', '60'],
  32526: ['Grey Wolf', 'Canine', 'Common', 'Grey Wolf Skin', '60'],
  32527: ['Brown Fox', 'Canine', 'Common', 'Brown Fox Skin', '60'],
  32528: ['Sheepdog', 'Canine', 'Common', 'Sheepdog Skin', '60'],
  32529: ['Grey Fox', 'Canine', 'Common', 'Grey Fox Skin', '60'],
  32530: ['Blue Parrot', 'Avian', 'Common', 'Blue Parrot Skin', '60'],
  32531: ['Oriole', 'Avian', 'Common', 'Oriole Skin', '60'],
  32532: ['Goldfinch', 'Avian', 'Common', 'Goldfinch Skin', '60'],
  32533: ['Bluebird', 'Avian', 'Common', 'Bluebird Skin', '60'],
  32534: ['Cardinal', 'Avian', 'Common', 'Cardinal Skin', '60'],
  32535: ['Elephant', 'Exotic', 'Common', 'Elephant Skin', '60'],
  32536: ['Koala', 'Exotic', 'Common', 'Koala Skin', '60'],
  32537: ['Monkey', 'Exotic', 'Common', 'Monkey Skin', '60'],
  32538: ['Chick', 'Farm', 'Common', 'Chick Skin', '60'],
  32539: ['Pig', 'Farm', 'Common', 'Pig Skin', '60'],
  32540: ['Duck', 'Farm', 'Common', 'Duck Skin', '60'],
  32541: ['Hamster', 'Woodland', 'Common', 'Hamster Skin', '60'],
  32542: ['Raccoon', 'Woodland', 'Common', 'Raccoon Skin', '60'],
  32543: ['Dino', 'Reptile', 'Common', 'Dino Skin', '60'],
  32544: ['Tomb Snake', 'Reptile', 'Common', 'Tomb Snake Skin', '60'],
  32545: ['Chameleon', 'Reptile', 'Common', 'Chameleon Skin', '60'],
  32547: ['Black Ant', 'Insect', 'Common', 'Black Ant Skin', '60'],
  32548: ['Blue Ant', 'Insect', 'Common', 'Blue Ant Skin', '60'],
  32549: ['Green Ant', 'Insect', 'Common', 'Green Ant Skin', '60'],
  32550: ['Red Ant', 'Insect', 'Common', 'Red Ant Skin', '60'],
  32551: ['Purple Ant', 'Insect', 'Common', 'Purple Ant Skin', '60'],
  32552: ['Penguin', 'Penguin', 'Common', 'Penguin Skin', '60'],
  32553: ['Green Penguin', 'Penguin', 'Common', 'Green Penguin Skin', '60'],
  32554: ['Grape Penguin', 'Penguin', 'Common', 'Grape Penguin Skin', '60'],
  32555: ['Grass Penguin', 'Penguin', 'Common', 'Grass Penguin Skin', '60'],
  32556: ['Blue Snail', 'Aquatic', 'Common', 'Blue Snail Skin', '60'],
  32557: ['Green Frog', 'Aquatic', 'Common', 'Green Frog Skin', '60'],
  32558: ['Purple Snail', 'Aquatic', 'Common', 'Purple Snail Skin', '60'],
  32559: ['Purple Frog', 'Aquatic', 'Common', 'Purple Frog Skin', '60'],
  32560: ['Sea Slurp', 'Aquatic', 'Common', 'Sea Slurp Skin', '60'],
  32561: ['Turtle', 'Aquatic', 'Common', 'Turtle Skin', '60'],
  32562: ['Crab', 'Aquatic', 'Common', 'Crab Skin', '60'],
  32564: ['Bat', 'Spooky', 'Common', 'Bat Skin', '60'],
  32565: ["Lil' Ghost", 'Spooky', 'Common', "Lil' Ghost Skin", '60'],
  32566: ['Spirit', 'Spooky', 'Common', 'Spirit Skin', '60'],
  32567: ['Baby', 'Humanoid', 'Common', 'Baby Skin', '60'],
  32569: ['Dreidel', '? ? ? ?', 'Common', 'Dreidel Skin', '60'],
  32570: ['Sprite Star', '? ? ? ?', 'Common', 'Sprite Star Skin', '60'],
  32571: ['Blue Thing', '? ? ? ?', 'Common', 'Blue Thing Skin', '60'],
  32572: ['Robobuddy', 'Automaton', 'Common', 'Robobuddy Skin', '60'],
  32573: ['Helmbot', 'Automaton', 'Common', 'Helmbot Skin', '60'],
  32574: ['Lion', 'Feline', 'Rare', 'Lion Skin', '80'],
  32575: ['White Lion', 'Feline', 'Rare', 'White Lion Skin', '80'],
  32576: ['Ninja Cat', 'Feline', 'Rare', 'Ninja Cat Skin', '80'],
  32577: ['Golden Sheepdog', 'Canine', 'Rare', 'Golden Sheepdog Skin', '80'],
  32578: ['Black Wolf', 'Canine', 'Rare', 'Black Wolf Skin', '80'],
  32579: ['Gold Bulldog', 'Canine', 'Rare', 'Gold Bulldog Skin', '80'],
  32580: ['Eagle', 'Avian', 'Rare', 'Eagle Skin', '80'],
  32581: ['Raven', 'Avian', 'Rare', 'Raven Skin', '80'],
  32582: ['USA Eagle', 'Avian', 'Rare', 'USA Eagle Skin', '80'],
  32583: ['Pigeon', 'Avian', 'Rare', 'Pigeon Skin', '80'],
  32584: ['Panda', 'Exotic', 'Rare', 'Panda Skin', '80'],
  32585: ['Toucan', 'Exotic', 'Rare', 'Toucan Skin', '80'],
  32586: ['Orangutan', 'Exotic', 'Rare', 'Orangutan Skin', '80'],
  32587: ['Mallard', 'Farm', 'Rare', 'Mallard Skin', '80'],
  32588: ['Turkey', 'Farm', 'Rare', 'Turkey Skin', '80'],
  32589: ['Skunk', 'Woodland', 'Rare', 'Skunk Skin', '80'],
  32590: ['Snowy Owl', 'Woodland', 'Rare', 'Snowy Owl Skin', '80'],
  32591: ['Reindeer', 'Woodland', 'Rare', 'Reindeer Skin', '80'],
  32592: ['Baby Dragon', 'Reptile', 'Rare', 'Baby Dragon Skin', '80'],
  32594: ['Bee', 'Insect', 'Rare', 'Bee Skin', '80'],
  32595: ['Praying Mantis', 'Insect', 'Rare', 'Praying Mantis Skin', '80'],
  32596: ['Karate Red', 'Penguin', 'Rare', 'Karate Red Skin', '80'],
  32597: ['Karate Blue', 'Penguin', 'Rare', 'Karate Blue Skin', '80'],
  32598: ['Karate Yellow', 'Penguin', 'Rare', 'Karate Yellow Skin', '80'],
  32599: ['Karate Purple', 'Penguin', 'Rare', 'Karate Purple Skin', '80'],
  32600: ['Demon Frog', 'Aquatic', 'Rare', 'Demon Frog Skin', '80'],
  32601: ['Peppermint Snail', 'Aquatic', 'Rare', 'Peppermint Snail Skin', '80'],
  32602: ['Gargoyle', 'Spooky', 'Rare', 'Gargoyle Skin', '80'],
  32603: ["Lil' Cyclops", 'Spooky', 'Rare', "Lil' Cyclops Skin", '80'],
  32604: ['Werewolf Cub', 'Spooky', 'Rare', 'Werewolf Cub Skin', '80'],
  32605: ['Monster Eye', 'Spooky', 'Rare', 'Monster Eye Skin', '80'],
  32606: ['Skull', 'Spooky', 'Rare', 'Skull Skin', '80'],
  32607: ['Leprechaun', 'Humanoid', 'Rare', 'Leprechaun Skin', '80'],
  32608: ['Elf', 'Humanoid', 'Rare', 'Elf Skin', '80'],
  32609: ['Mermaid', 'Humanoid', 'Rare', 'Mermaid Skin', '80'],
  32610: ['Jelly', '? ? ? ?', 'Rare', 'Jelly Skin', '80'],
  32611: ['Gummy Bear', '? ? ? ?', 'Rare', 'Gummy Bear Skin', '80'],
  32612: ['Snowman', '? ? ? ?', 'Rare', 'Snowman Skin', '80'],
  32613: ['Jalapeno', '? ? ? ?', 'Rare', 'Jalapeno Skin', '80'],
  32614: ['Redbot', 'Automaton', 'Rare', 'Redbot Skin', '80'],
  32615: ['Funkatron', 'Automaton', 'Rare', 'Funkatron Skin', '80'],
  32616: ['Tiger', 'Feline', 'Divine', 'Tiger Skin', '80'],
  32617: ['Pink Lion', 'Feline', 'Divine', 'Pink Lion Skin', '80'],
  32618: ['Midnight Wolf', 'Canine', 'Divine', 'Midnight Wolf Skin', '80'],
  32619: ['Golden Hyena', 'Canine', 'Divine', 'Golden Hyena Skin', '80'],
  32620: ['Phoenix', 'Avian', 'Divine', 'Phoenix Skin', '80'],
  32621: ['Griffin', 'Avian', 'Divine', 'Griffin Skin', '80'],
  32622: ['War Elephant', 'Exotic', 'Divine', 'War Elephant Skin', '80'],
  32623: ['King Gorilla', 'Exotic', 'Divine', 'King Gorilla Skin', '80'],
  32624: ['Enraged Yack', 'Farm', 'Divine', 'Enraged Yack Skin', '80'],
  32625: ['Night Mare', 'Farm', 'Divine', 'Night Mare Skin', '80'],
  32626: ['Silver Doe', 'Woodland', 'Divine', 'Silver Doe Skin', '80'],
  32627: ['Solar Owl', 'Woodland', 'Divine', 'Solar Owl Skin', '80'],
  32628: ['Tandem Cobra', 'Reptile', 'Divine', 'Tandem Cobra Skin', '80'],
  32629: ['Poison Drake', 'Reptile', 'Divine', 'Poison Drake Skin', '80'],
  32630: ['Beetleman', 'Insect', 'Divine', 'Beetleman Skin', '80'],
  32631: ['Ultrawasp', 'Insect', 'Divine', 'Ultrawasp Skin', '80'],
  32632: ['Battle Penguin', 'Penguin', 'Divine', 'Battle Penguin Skin', '80'],
  32633: ['Tank Penguin', 'Penguin', 'Divine', 'Tank Penguin Skin', '80'],
  32634: ['Golden Crab', 'Aquatic', 'Divine', 'Golden Crab Skin', '80'],
  32635: ['Great Shark', 'Aquatic', 'Divine', 'Great Shark Skin', '80'],
  32636: ['Blue Landfish', 'Aquatic', 'Divine', 'Blue Landfish Skin', '80'],
  32637: ['Glowing Skull', 'Spooky', 'Divine', 'Glowing Skull Skin', '80'],
  32638: ['Monkey Head', 'Spooky', 'Divine', 'Monkey Head Skin', '80'],
  32639: ['Reaper', 'Spooky', 'Divine', 'Reaper Skin', '80'],
  32640: ['Battle God', 'Humanoid', 'Divine', 'Battle God Skin', '80'],
  32641: ['Centaur', 'Humanoid', 'Divine', 'Centaur Skin', '80'],
  32642: ['Forest Fairy', 'Humanoid', 'Divine', 'Forest Fairy Skin', '80'],
  32643: ["Lil' Oryx", '? ? ? ?', 'Divine', "Lil' Oryx Skin", '60'],
  32644: ['Shroom', '? ? ? ?', 'Divine', 'Shroom Skin', '80'],
  32645: ['Great Jelly', '? ? ? ?', 'Divine', 'Great Jelly Skin', '80'],
  32646: ['Spiderbot', 'Automaton', 'Divine', 'Spiderbot Skin', '80'],
  32647: ['Cylindron', 'Automaton', 'Divine', 'Cylindron Skin', '80'],
  32648: ['Gutsbot', 'Automaton', 'Divine', 'Gutsbot Skin', '80'],
  32649: ['Squirrel', 'Woodland', 'Common', 'Squirrel Skin', '60'],
  32650: ['Dragonfly', 'Insect', 'Common', 'Dragonfly Skin', '60'],
  32651: ['Pumpkin Head', 'Spooky', 'Divine', 'Pumpkin Head Skin', '60'],
  32668: ['Christmas Tree', '? ? ? ?', 'Divine', 'Christmas Tree Skin', '80'],
  32670: ['Red Nose', 'Woodland', 'Divine', 'Red Nose Skin', '80'],
  32703: ['Red Bagston', '? ? ? ?', 'Divine', 'Red Bagston Skin', '80'],
  32706: ['Helper Bagston', '? ? ? ?', 'Divine', 'Helper Bagston Skin', '80'],
  32709: ['Red Helper Bagston', '? ? ? ?', 'Divine', 'Red Helper Bagston Skin', '80'],
  32713: ['Muddy Tidechaser', 'Humanoid', 'Common', 'Muddy Tidechaser Skin', '60'],
  32763: ['Giant Vampire Bat', 'Spooky', 'Divine', 'Giant Vampire Bat Skin', '80'],
  34606: ['Chibi Oryx Gladiator', 'Humanoid', 'Divine', 'Chibi Oryx Gladiator Skin', '80'],
  34611: ['Crucible Pet Rock', 'Restricted', 'Divine', 'Crucible Pet Rock Skin', '80'],
  34802: ['Sturdy Beer Barrel', '? ? ? ?', 'Divine', 'Sturdy Beer Barrel Skin', '80'],
  34805: ['Wolpertinger', 'Farm', 'Divine', 'Wolpertinger Skin', '80'],
  34808: ['Happy Dog', 'Canine', 'Divine', 'Happy Dog Skin', '80'],
  35077: ['Kelpie', 'Aquatic', 'Divine', 'Kelpie Skin', '80'],
  35080: ['Hydra', 'Reptile', 'Divine', 'Hydra Skin', '80'],
  35083: ['Ancient Gryphon', 'Avian', 'Divine', 'Ancient Gryphon Skin', '80'],
  35086: ['Ancient Chimera', 'Feline', 'Divine', 'Ancient Chimera Skin', '80'],
  35089: ['Ancient Pegasus', 'Farm', 'Divine', 'Ancient Pegasus Skin', '80'],
  35092: ['Gingerbread Golem', '? ? ? ?', 'Divine', 'Gingerbread Golem Skin', '80'],
  35095: ['Fluffy Snowy Owl', 'Avian', 'Divine', 'Fluffy Snowy Owl Skin', '80'],
  35098: ['Little Helper Bot', 'Automaton', 'Divine', 'Little Helper Bot Skin', '80'],
  35101: ['Oryxmas Tree', 'Woodland', 'Divine', 'Oryxmas Tree Skin', '80'],
  35104: ['Strange Bunny', 'Farm', 'Divine', 'Strange Bunny Skin', '80'],
  35107: ['Quasar Pup', 'Canine', 'Divine', 'Quasar Pup Skin', '80'],
  35110: ['Caged Prisoner', 'Spooky', 'Divine', 'Caged Prisoner Skin', '80'],
  35113: ['Zodiac Dragon', 'Reptile', 'Divine', 'Zodiac Dragon Skin', '80'],
  35116: ['Baby Blue Dragon', 'Reptile', 'Divine', 'Baby Blue Dragon Skin', '80'],
  35119: ['Harpist Demon', 'Humanoid', 'Divine', 'Harpist Demon Skin', '80'],
  35122: ['Chaos Dragon', 'Reptile', 'Divine', 'Chaos Dragon Skin', '80'],
  35125: ['Mini Pyyr', 'Reptile', 'Divine', 'Mini Pyyr Skin', '80'],
  35128: ['Penguin Cupid', 'Penguin', 'Divine', 'Penguin Cupid Skin', '80'],
  41268: ['Group of Rats', 'Woodland', 'Divine', 'Group of Rats Pet Skin', '80'],
  41284: ['Gold Primal Snake', 'Reptile', 'Divine', 'Gold Primal Snake Pet Skin', '80'],
  41287: ['Silver Primal Snake', 'Reptile', 'Divine', 'Silver Primal Snake Pet Skin', '80'],
  41290: ['Pink Serpent', 'Reptile', 'Divine', 'Pink Serpent Pet Skin', '80'],
  41293: ['Purple Serpent', 'Reptile', 'Divine', 'Purple Serpent Pet Skin', '80'],
  41296: ['Blue Serpent', 'Reptile', 'Divine', 'Blue Serpent Pet Skin', '80'],
  41299: ['Green Serpent', 'Reptile', 'Divine', 'Green Serpent Pet Skin', '80'],
  41302: ['Yellow Serpent', 'Reptile', 'Divine', 'Yellow Serpent Pet Skin', '80'],
  41305: ['Orange Serpent', 'Reptile', 'Divine', 'Orange Serpent Pet Skin', '80'],
  41308: ['Red Serpent', 'Reptile', 'Divine', 'Red Serpent Pet Skin', '80'],
  41311: ['White Serpent', 'Reptile', 'Divine', 'White Serpent Pet Skin', '80'],
  41320: ['Poisoned Apple', 'Spooky', 'Divine', 'Poisoned Apple Pet Skin', '80'],
  41325: ['Fabulous Unicorn', 'Farm', 'Divine', 'Fabulous Unicorn Pet Skin', '80'],
  41341: ['Chibi Ghost of Oryxmas', 'Humanoid', 'Divine', 'Chibi Ghost of Oryxmas Skin', '80'],
  41347: ['Yule Cnidarian', '? ? ? ?', 'Divine', 'Yule Cnidarian Skin', '80'],
  41350: ['Ice Sculpture Penguin', 'Penguin', 'Divine', 'Ice Sculpture Penguin Skin', '80'],
  41353: ['Beefcake Elf', 'Humanoid', 'Divine', 'Beefcake Elf Skin', '80'],
  41362: ['Holly Reindeer', 'Woodland', 'Divine', 'Holly Reindeer Skin', '80'],
  41365: [
    'Snowball Rolling Knight Companion',
    'Humanoid',
    'Divine',
    'Snowball Rolling Knight Companion Skin',
    '80'
  ],
  41368: [
    'Ice Cube Frozen Crown Companion',
    '? ? ? ?',
    'Divine',
    'Ice Cube Frozen Crown Companion Skin',
    '80'
  ],
  41404: ['Cursed Raven', 'Avian', 'Divine', 'Cursed Raven Skin', '80'],
  41455: ['Wooden Frog Companion', 'Aquatic', 'Divine', 'Cursed Raven Skin', '80'],
  41489: [
    "Belladonna's Flower Buddy",
    '? ? ? ?',
    'Divine',
    "Belladonna's Flower Buddy Pet Skin",
    '80'
  ],
  44369: ['Penitent Frog', 'Aquatic', 'Divine', 'Penitent Frog Pet Skin', '80'],
  50288: ['Toy Bot K.B', 'Automaton', 'Divine', 'Toy Bot K.B Pet Skin', '80'],
  50291: ['Kogbold Maid', 'Reptile', 'Divine', 'Kogbold Maid Pet Skin', '80'],
  50698: ['Zodiac Bunny', 'Farm', 'Divine', 'Zodiac Bunny Pet Skin', '80'],
  50701: ['Model K999', 'Canine', 'Divine', 'Model K999 Pet Skin', '80'],
  50704: ['Gentle Unicorn', 'Farm', 'Divine', 'Gentle Unicorn Pet Skin', '80'],
  50707: ['Genie Lamp', 'Humanoid', 'Divine', 'Genie Lamp Pet Skin', '80'],
  50713: ['King Cobra', 'Reptile', 'Divine', 'King Cobra Pet Skin', '80'],
  50716: ['Chibi Kitsune Umi', 'Humanoid', 'Divine', 'Chibi Kitsune Umi Pet Skin', '80'],
  50719: ['Abyssal Crab', 'Aquatic', 'Divine', 'Abyssal Crab Pet Skin', '80'],
  50722: ['Cryophoenix', 'Avian', 'Divine', 'Cryophoenix Pet Skin', '80'],
  50725: ['Spectral Raven', 'Avian', 'Divine', 'Spectral Raven Pet Skin', '80'],
  50728: ['Void Child', 'Humanoid', 'Divine', 'Void Child Pet Skin', '80'],
  50731: ['Gelatinous Warrior', '? ? ? ?', 'Divine', 'Gelatinous Warrior Pet Skin', '80'],
  50734: ['Karate Pug', 'Canine', 'Divine', 'Karate Pug Pet Skin', '80'],
  50737: ['Echo of a Hero', 'Humanoid', 'Divine', 'Echo of a Hero Pet Skin', '80'],
  51289: ['Chibi Leprechaun', 'Humanoid', 'Divine', 'Chibi Leprechaun Skin', '80'],
  51292: ['Wondrous Basket', 'Farm', 'Divine', 'Wondrous Basket Skin', '80'],
  51295: ['Eggstravagant Egg', 'Farm', 'Divine', 'Eggstravagant Egg Skin', '80'],
  51298: ["Biff's Best Friend", 'Canine', 'Divine', "Biff's Best Friend Skin", '80'],
  51301: [
    "Manager's Best Friend Alice",
    'Canine',
    'Divine',
    "Manager's Best Friend Alice Skin",
    '80'
  ],
  51338: ['Cracked Egg', 'Exotic', 'Divine', 'Cracked Egg Skin', '80'],
  51426: ['Nile Crocodile', 'Reptile', 'Divine', 'Nile Crocodile Skin', '80'],
  51429: ['Chibi Penguin Mummy', 'Penguin', 'Divine', 'Chibi Penguin Mummy Skin', '80'],
  51432: ['Sphinx Guardian', 'Humanoid', 'Divine', 'Sphinx Guardian Skin', '80'],
  51489: ['Red Hot Scarab', 'Insect', 'Divine', 'Red Hot Scarab Skin', '80'],
  51494: ['Sunflower Scarab', 'Insect', 'Divine', 'Sunflower Scarab Skin', '80'],
  51551: [
    'Chibi Avatar of the Forgotten King',
    'Spooky',
    'Divine',
    'Chibi Avatar of the Forgotten King Skin',
    '80'
  ],
  51554: [
    'Chibi Avatar of the Accursed King',
    'Spooky',
    'Divine',
    'Chibi Avatar of the Accursed King Skin',
    '80'
  ],
  51561: ['Deep Sea Companion', 'Aquatic', 'Divine', 'Deep Sea Companion Skin', '80'],
  51564: ['Mushroom Buddy', 'Woodland', 'Divine', 'Mushroom Buddy Skin', '80'],
  51667: ['Hermit Crab', 'Aquatic', 'Divine', 'Hermit Crab Skin', '80'],
  51719: ['the Void Star', '? ? ? ?', 'Divine', 'The Void Star Skin', '80'],
  51799: ['Imperial Eagle', 'Avian', 'Divine', 'Imperial Eagle Skin', '80'],
  51814: ["Wanderer's Portal", '? ? ? ?', 'Divine', "Wanderer's Portal Skin", '80'],
  51817: ['Shady Slurp', '? ? ? ?', 'Divine', 'Shady Slurp Skin', '80'],
  51820: ['Wandering Slurp', '? ? ? ?', 'Divine', 'Wandering Slurp Skin', '80'],
  51823: ['Pirate Queen Slurp', '? ? ? ?', 'Divine', 'Pirate Queen Slurp Skin', '80'],
  51826: ['Black Blade Slurp', '? ? ? ?', 'Divine', 'Black Blade Slurp Skin', '80'],
  51829: ['Grand Shaman Slurp', '? ? ? ?', 'Divine', 'Grand Shaman Slurp Skin', '80'],
  51832: ['Pharaoh Slurp', '? ? ? ?', 'Divine', 'Pharaoh Slurp Skin', '80'],
  51880: ['Cursed Dirk', '? ? ? ?', 'Divine', 'Cursed Dirk Skin', '80'],
  51903: ['Magical Book', 'Spooky', 'Divine', 'Magical Book Skin', '80'],
  51906: ['Enchanted Inkwell', 'Spooky', 'Divine', 'Enchanted Inkwell Skin', '80'],
  51909: ['Friendly Pencil', 'Spooky', 'Divine', 'Friendly Pencil Skin', '80'],
  51925: ['Noble Canine', 'Canine', 'Divine', 'Noble Canine Skin', '80'],
  51958: ['Vampire Bat Pet', 'Spooky', 'Divine', 'Vampire Bat Pet Skin', '80'],
  51961: ['Haunted Cat', 'Feline', 'Divine', 'Haunted Cat Skin', '80'],
  51976: ['Chibi Pilgrim', 'Humanoid', 'Divine', 'Chibi Pilgrim Skin', '80'],
  51979: ['Cauldron Spirit', 'Spooky', 'Divine', 'Cauldron Spirit Skin', '80'],
  51982: ['Archmage Craig', 'Spooky', 'Divine', 'Archmage Craig Skin', '80'],
  52047: ['Angelic Cat', 'Feline', 'Divine', 'Angelic Cat Skin', '80'],
  52051: ['Giving Pixie', 'Woodland', 'Divine', 'Giving Pixie Skin', '80'],
  52098: [
    'Knockout King Action Figure',
    'Aquatic',
    'Rare',
    'Knockout King Action Figure Skin',
    null
  ],
  52210: [
    'Stone Judoka Action Figure',
    'Spooky',
    'Rare',
    'Stone Judoka Action Figure Pet Skin',
    null
  ],
  52271: ['Jolly Chimp', 'Exotic', 'Divine', 'Jolly Chimp Pet Skin', '80'],
  811318: ['Flying Carpet', 'Spooky', 'Divine', 'Flying Carpet Pet Skin', '80']
};
