// type: ["id", "DisplayId", "ItemTier", "Family", "Rarity"]
export const petSkins = {
  606: ['Axolotl Pet Skin', 'Axolotl', 3, 'Exotic', 'Common', 195, false, 'chars8x8rPets1'],
  1900: ['Cockatoo Pet Skin', 'Cockatoo', 2, 'Avian', 'Rare', 202, false, 'chars8x8rPets1'],
  2223: [
    'Killer Bee Queen Skin',
    'Killer Bee Queen',
    2,
    'Insect',
    'Divine',
    13,
    true,
    'epicHiveChars16x16'
  ],
  2382: ['Pigboot Pet Skin', 'Pigboot', 3, 'Woodland', 'Rare', 196, false, 'chars8x8rPets1'],
  3012: ['Platypus Pet Skin', 'Platypus', 3, 'Aquatic', 'Rare', 198, false, 'chars8x8rPets1'],
  3015: ['Walrus Pet Skin', 'Walrus', 4, 'Aquatic', 'Rare', 199, false, 'chars8x8rPets1'],
  3515: ['Blue Jay Pet Skin', 'Blue Jay', 2, 'Avian', 'Common', 200, false, 'chars8x8rPets1'],
  3518: ['Vulture Pet Skin', 'Vulture', 2, 'Avian', 'Rare', 201, false, 'chars8x8rPets1'],
  3597: ['Seal Pet Skin', 'Seal', null, 'Aquatic', 'Rare', 197, false, 'chars8x8rPets1'],
  3660: ['Kiwi Pet Skin', 'Kiwi', 2, 'Exotic', 'Common', 206, false, 'chars8x8rPets1'],
  3686: [
    'Zebra Spider Pet Skin',
    'Zebra Spider',
    null,
    'Insect',
    'Rare',
    221,
    false,
    'chars8x8rPets1'
  ],
  3689: [
    'Violet Larva Pet Skin',
    'Violet Larva',
    null,
    'Insect',
    'Common',
    222,
    false,
    'chars8x8rPets1'
  ],
  4091: [
    'Blue Butterfly Pet Skin',
    'Blue Butterfly',
    3,
    'Insect',
    'Rare',
    214,
    false,
    'chars8x8rPets1'
  ],
  4094: [
    'Pink Butterfly Pet Skin',
    'Pink Butterfly',
    4,
    'Insect',
    'Rare',
    215,
    false,
    'chars8x8rPets1'
  ],
  5883: [
    'Verdant Larva Pet Skin',
    'Verdant Larva',
    null,
    'Insect',
    'Common',
    218,
    false,
    'chars8x8rPets1'
  ],
  5886: ['Ladybug Pet Skin', 'Ladybug', 3, 'Insect', 'Rare', 219, false, 'chars8x8rPets1'],
  6054: [
    'Autumn Hedgehog Skin',
    'Autumn Hedgehog',
    2,
    'Woodland',
    'Rare',
    162,
    false,
    'chars8x8rPets1'
  ],
  6057: [
    'Mini Ghost Ship Skin',
    'Mini Ghost Ship',
    1,
    '? ? ? ?',
    'Rare',
    163,
    false,
    'chars8x8rPets1'
  ],
  6066: [
    'Mini Model Ship Skin',
    'Mini Model Ship',
    null,
    '? ? ? ?',
    'Rare',
    164,
    false,
    'chars8x8rPets1'
  ],
  6069: ['Healbot Skin', 'Healbot', null, 'Automaton', 'Rare', 165, false, 'chars8x8rPets1'],
  6072: ['Sugar Skull Skin', 'Sugar Skull', null, 'Spooky', 'Rare', 166, false, 'chars8x8rPets1'],
  6075: ['Cow Pet Skin', 'Cow', 2, 'Farm', 'Rare', 208, false, 'chars8x8rPets1'],
  6078: ['White Duck Pet Skin', 'White Duck', 2, 'Farm', 'Rare', 209, false, 'chars8x8rPets1'],
  6081: [
    'Senor Skeleton Skin',
    'Se\u00f1or Skeleton',
    null,
    'Spooky',
    'Rare',
    167,
    false,
    'chars8x8rPets1'
  ],
  6084: [
    'Flying Eyeball Skin',
    'Flying Eyeball',
    2,
    'Spooky',
    'Rare',
    168,
    false,
    'chars8x8rPets1'
  ],
  6087: ['Mini Cauldron Skin', 'Mini Cauldron', 1, 'Spooky', 'Rare', 169, false, 'chars8x8rPets1'],
  6091: [
    'Little Tiger Pet Skin',
    'Little Tiger',
    2,
    'Feline',
    'Rare',
    212,
    false,
    'chars8x8rPets1'
  ],
  6094: ['Worm Pet Skin', 'Worm', 2, 'Insect', 'Common', 213, false, 'chars8x8rPets1'],
  6096: ["Doom's Steed Skin", "Doom's Steed", 2, 'Spooky', 'Rare', 47, false, 'petsDivine'],
  6099: ['Lichwyrm Skin', 'Lichwyrm', 3, 'Spooky', 'Divine', 48, false, 'petsDivine'],
  6102: ['Cauldron Skin', 'Cauldron', 2, 'Spooky', 'Divine', 49, false, 'petsDivine'],
  6379: ['Bear Pet Skin', 'Bear', null, 'Woodland', 'Rare', 216, false, 'chars8x8rPets1'],
  6382: ['Moose Pet Skin', 'Moose', 3, 'Woodland', 'Rare', 217, false, 'chars8x8rPets1'],
  6581: [
    'Frilled Lizard Skin',
    'Frilled Lizard',
    null,
    'Reptile',
    'Rare',
    106,
    false,
    'chars8x8rPets1'
  ],
  6591: ['Fire Rooster Skin', 'Fire Rooster', 2, 'Farm', 'Rare', 118, false, 'chars8x8rPets1'],
  6594: [
    'Rooster of Good Fortune Skin',
    'Rooster of Good Fortune',
    3,
    'Farm',
    'Divine',
    119,
    false,
    'chars8x8rPets1'
  ],
  6597: [
    'Mini Chinese Dragon Skin',
    'Red Dragon',
    3,
    'Reptile',
    'Rare',
    120,
    false,
    'chars8x8rPets1'
  ],
  6600: [
    'Gingerbread Man Skin',
    'Gingerbread Man',
    1,
    '? ? ? ?',
    'Rare',
    121,
    false,
    'chars8x8rPets1'
  ],
  6603: [
    'Mini Polaris Skin',
    'Mini Polaris',
    null,
    '? ? ? ?',
    'Rare',
    122,
    false,
    'chars8x8rPets1'
  ],
  6606: [
    'Mini Paper Lantern Skin',
    'Mini Paper Lantern',
    2,
    '? ? ? ?',
    'Divine',
    35,
    false,
    'petsDivine'
  ],
  6609: ['Paper Lantern Skin', 'Paper Lantern', 2, '? ? ? ?', 'Divine', 36, false, 'petsDivine'],
  6612: ['Chinese Dragon Skin', 'Chinese Dragon', 3, 'Reptile', 'Divine', 37, false, 'petsDivine'],
  6615: ['Desert Cobra Skin', 'Desert Cobra', 2, 'Reptile', 'Rare', 123, false, 'chars8x8rPets1'],
  6705: ['Mini Medusa Pet Skin', 'Mini Medusa', 3, 'Reptile', 'Rare', 228, false, 'chars8x8rPets1'],
  6708: ['Mini Djinn Pet Skin', 'Mini Djinn', 2, 'Humanoid', 'Rare', 229, false, 'chars8x8rPets1'],
  6711: [
    'Mini Ghost God Pet Skin',
    'Mini Ghost God',
    3,
    'Spooky',
    'Rare',
    230,
    false,
    'chars8x8rPets1'
  ],
  6714: [
    'Mini Flying Brain Pet Skin',
    'Mini Flying Brain',
    2,
    'Spooky',
    'Rare',
    231,
    false,
    'chars8x8rPets1'
  ],
  6717: [
    'Mini Beholder Pet Skin',
    'Mini Beholder',
    3,
    'Spooky',
    'Rare',
    232,
    false,
    'chars8x8rPets1'
  ],
  6720: [
    'Mini Sprite God Pet Skin',
    'Mini Sprite God',
    3,
    '? ? ? ?',
    'Rare',
    233,
    false,
    'chars8x8rPets1'
  ],
  6723: [
    'Mini Ent God Pet Skin',
    'Mini Ent God',
    3,
    'Woodland',
    'Rare',
    234,
    false,
    'chars8x8rPets1'
  ],
  6726: [
    'Mini Slime God Pet Skin',
    'Mini Slime God',
    3,
    '? ? ? ?',
    'Rare',
    235,
    false,
    'chars8x8rPets1'
  ],
  6729: [
    'Mini White Demon Pet Skin',
    'Mini White Demon',
    3,
    'Spooky',
    'Rare',
    236,
    false,
    'chars8x8rPets1'
  ],
  8389: ['Pillbug Pet Skin', 'Pillbug', 2, 'Insect', 'Rare', 223, false, 'chars8x8rPets1'],
  8593: [
    'Brown Bulldog Pet Skin',
    'Brown Bulldog',
    3,
    'Canine',
    'Rare',
    203,
    false,
    'chars8x8rPets1'
  ],
  8596: [
    'White Bulldog Pet Skin',
    'White Bulldog',
    4,
    'Canine',
    'Rare',
    204,
    false,
    'chars8x8rPets1'
  ],
  8599: ['Dingo Pet Skin', 'Dingo', 2, 'Canine', 'Rare', 205, false, 'chars8x8rPets1'],
  8662: ['Red Parrot Pet Skin', 'Red Parrot', 2, 'Exotic', 'Rare', 207, false, 'chars8x8rPets1'],
  8709: ['Cheetah Pet Skin', 'Cheetah', 2, 'Feline', 'Rare', 210, false, 'chars8x8rPets1'],
  8712: ['Jaguar Pet Skin', 'Jaguar', 2, 'Feline', 'Rare', 211, false, 'chars8x8rPets1'],
  9163: ['Floomp Skin', 'Floomp', 3, 'Reptile', 'Divine', 59, false, 'petsDivine'],
  9167: [
    'Vermilion Dragon Skin',
    'Vermilion Dragon',
    4,
    'Reptile',
    'Divine',
    60,
    false,
    'petsDivine'
  ],
  9171: ['Golden Capricorn Skin', 'Golden Capricorn', 4, 'Farm', 'Divine', 61, false, 'petsDivine'],
  9174: [
    'Golden Sagittarius Skin',
    'Golden Sagittarius',
    3,
    'Humanoid',
    'Divine',
    62,
    false,
    'petsDivine'
  ],
  9177: [
    'Golden Aquarius Skin',
    'Golden Aquarius',
    3,
    'Humanoid',
    'Divine',
    63,
    false,
    'petsDivine'
  ],
  9180: ['Capricorn Skin', 'Capricorn', 3, 'Farm', 'Divine', 64, false, 'petsDivine'],
  9183: ['Sagittarius Skin', 'Sagittarius', 3, 'Humanoid', 'Divine', 65, false, 'petsDivine'],
  9187: ['Aquarius Skin', 'Aquarius', 4, 'Humanoid', 'Divine', 66, false, 'petsDivine'],
  9190: [
    'Bouncing Slime Skin',
    'Bouncing Slime',
    null,
    '? ? ? ?',
    'Rare',
    184,
    false,
    'chars8x8rPets1'
  ],
  9193: [
    'Mini Pot Of Gold Skin',
    'Mini Pot Of Gold',
    2,
    '? ? ? ?',
    'Rare',
    185,
    false,
    'chars8x8rPets1'
  ],
  9196: [
    "Leprechaun's Walking Hat Skin",
    "Leprechaun's Walking Hat",
    2,
    '? ? ? ?',
    'Rare',
    186,
    false,
    'chars8x8rPets1'
  ],
  9199: [
    'Rainbow Rocketeer Skin',
    'Rainbow Rocketeer',
    2,
    'Humanoid',
    'Divine',
    67,
    false,
    'petsDivine'
  ],
  9252: ['Tuxedo Bird Pet Skin', 'Tuxedo Bird', 3, 'Avian', 'Rare', 69, false, 'petsDivine'],
  9255: ['Flamingo Pet Skin', 'Flamingo', null, 'Exotic', 'Divine', 70, false, 'petsDivine'],
  9258: ['Heron Pet Skin', 'Heron', 2, 'Avian', 'Divine', 71, false, 'petsDivine'],
  9261: [
    'Angelic Drake Pet Skin',
    'Angelic Drake',
    2,
    'Reptile',
    'Divine',
    72,
    false,
    'petsDivine'
  ],
  9264: [
    'Demonic Drake Pet Skin',
    'Demonic Drake',
    null,
    'Reptile',
    'Divine',
    73,
    false,
    'petsDivine'
  ],
  9267: [
    'Fusion Golem Pet Skin',
    'Fusion Golem',
    4,
    'Automaton',
    'Divine',
    74,
    false,
    'petsDivine'
  ],
  9270: [
    'Vibrant Seadragon Pet Skin',
    'Vibrant Seadragon',
    null,
    'Aquatic',
    'Divine',
    75,
    false,
    'petsDivine'
  ],
  9273: ['Arthro-bot Pet Skin', 'Arthro-bot', 3, 'Automaton', 'Rare', 188, false, 'chars8x8rPets1'],
  9276: ['Mini Biff Pet Skin', 'Mini Biff', 3, 'Farm', 'Rare', 189, false, 'chars8x8rPets1'],
  9279: [
    'Newborn Chick Pet Skin',
    'Newborn Chick',
    2,
    'Farm',
    'Rare',
    190,
    false,
    'chars8x8rPets1'
  ],
  9282: ['Amazon Pet Skin', 'Amazon', 2, 'Exotic', 'Rare', 191, false, 'chars8x8rPets1'],
  9285: ['Party Crow Pet Skin', 'Party Crow', 2, 'Avian', 'Rare', 192, false, 'chars8x8rPets1'],
  9288: [
    'Honey-bot Ant Pet Skin',
    'Honey-bot Ant',
    3,
    'Automaton',
    'Rare',
    193,
    false,
    'chars8x8rPets1'
  ],
  9291: [
    'Fountain Child Pet Skin',
    'Fountain Child',
    1,
    'Humanoid',
    'Rare',
    194,
    false,
    'chars8x8rPets1'
  ],
  9294: [
    'Desert Scorpion Pet Skin',
    'Desert Scorpion',
    2,
    'Insect',
    'Divine',
    76,
    false,
    'petsDivine'
  ],
  9297: [
    'Giant Centipede Pet Skin',
    'Giant Centipede',
    4,
    'Insect',
    'Divine',
    77,
    false,
    'petsDivine'
  ],
  9300: [
    'Silver Sky Serpent Pet Skin',
    'Silver Sky Serpent',
    2,
    'Reptile',
    'Divine',
    78,
    false,
    'petsDivine'
  ],
  9305: [
    'Twilight Angler Pet Skin',
    'Twilight Angler',
    4,
    'Aquatic',
    'Divine',
    79,
    false,
    'petsDivine'
  ],
  9308: [
    'Abyss Goliath Pet Skin',
    'Abyss Goliath',
    4,
    'Reptile',
    'Divine',
    80,
    false,
    'petsDivine'
  ],
  9741: ['Little Fox Pet Skin', 'Little Fox', 4, 'Canine', 'Rare', 242, false, 'chars8x8rPets1'],
  9744: [
    'Mini Beer God Pet Skin',
    'Mini Beer God',
    4,
    'Humanoid',
    'Rare',
    243,
    false,
    'chars8x8rPets1'
  ],
  9747: [
    'Titanium Rex Pet Skin',
    'Titanium Rex',
    4,
    'Automaton',
    'Divine',
    88,
    false,
    'petsDivine'
  ],
  9750: ['Red Panda Pet Skin', 'Red Panda', 4, 'Exotic', 'Divine', 89, false, 'petsDivine'],
  9753: ['Gargantua Pet Skin', 'Gargantua', 4, 'Reptile', 'Divine', 90, false, 'petsDivine'],
  10913: [
    'White Bounsheep Skin',
    'White Bounsheep',
    2,
    'Farm',
    'Rare',
    124,
    false,
    'chars8x8rPets1'
  ],
  10916: [
    'Grey Bounsheep Skin',
    'Grey Bounsheep',
    null,
    'Farm',
    'Rare',
    125,
    false,
    'chars8x8rPets1'
  ],
  10919: [
    'Brown Bounsheep Skin',
    'Brown Bounsheep',
    null,
    'Farm',
    'Rare',
    126,
    false,
    'chars8x8rPets1'
  ],
  10922: [
    "Bes' Artifact Skin",
    "Bes' Artifact",
    2,
    '? ? ? ?',
    'Rare',
    127,
    false,
    'chars8x8rPets1'
  ],
  10925: [
    "Geb's Artifact Skin",
    "Geb's Artifact",
    2,
    '? ? ? ?',
    'Rare',
    128,
    false,
    'chars8x8rPets1'
  ],
  10928: [
    "Nut's Artifact Skin",
    "Nut's Artifact",
    2,
    '? ? ? ?',
    'Rare',
    129,
    false,
    'chars8x8rPets1'
  ],
  14096: [
    'Skelly Penguin Pet Skin',
    'Skelly Penguin',
    2,
    'Penguin',
    'Rare',
    227,
    false,
    'chars8x8rPets1'
  ],
  14099: [
    'Reticulated Longuin Pet Skin',
    'Reticulated Longuin',
    4,
    'Penguin',
    'Divine',
    82,
    false,
    'petsDivine'
  ],
  14102: [
    'Transcendent Penguin Pet Skin',
    'Transcendent Penguin',
    4,
    'Penguin',
    'Divine',
    83,
    false,
    'petsDivine'
  ],
  14105: [
    'Aeronautical Penguin Pet Skin',
    'Aeronautical Penguin',
    3,
    'Penguin',
    'Divine',
    84,
    false,
    'petsDivine'
  ],
  15712: [
    'Good Mask Spirit Pet Skin',
    'Good Mask Spirit',
    4,
    'Exotic',
    'Divine',
    86,
    false,
    'petsDivine'
  ],
  15715: [
    'Evil Mask Spirit Pet Skin',
    'Evil Mask Spirit',
    3,
    'Exotic',
    'Divine',
    87,
    false,
    'petsDivine'
  ],
  19140: ['Mini Sphinx Skin', 'Mini Sphinx', 2, '? ? ? ?', 'Rare', 130, false, 'chars8x8rPets1'],
  19142: [
    'Mini Crystal Steed Skin',
    'Mini Crystal Steed',
    2,
    '? ? ? ?',
    'Rare',
    131,
    false,
    'chars8x8rPets1'
  ],
  19144: [
    'Carnivorous Plant Skin',
    'Carnivorous Plant',
    2,
    '? ? ? ?',
    'Rare',
    132,
    false,
    'chars8x8rPets1'
  ],
  19146: [
    'Knight Companion Skin',
    'Knight Companion',
    null,
    '? ? ? ?',
    'Divine',
    133,
    false,
    'chars8x8rPets1'
  ],
  19148: [
    'Mr Cactus Jr. Skin',
    'Mr Cactus Jr.',
    2,
    '? ? ? ?',
    'Rare',
    134,
    false,
    'chars8x8rPets1'
  ],
  19150: ['Mr Cactus Skin', 'Mr Cactus', 3, '? ? ? ?', 'Divine', 38, false, 'petsDivine'],
  19383: ['Mini Limon Skin', 'Mini Limon', 3, '? ? ? ?', 'Rare', 135, false, 'chars8x8rPets1'],
  19462: [
    'Mini Stone Oryx Skin',
    'Mini Stone Oryx',
    null,
    '? ? ? ?',
    'Rare',
    136,
    false,
    'chars8x8rPets1'
  ],
  19465: [
    'Mini Gigacorn Skin',
    'Mini Gigacorn',
    3,
    '? ? ? ?',
    'Rare',
    137,
    false,
    'chars8x8rPets1'
  ],
  19468: [
    'Mini Creampuff Skin',
    'Mini Creampuff',
    3,
    '? ? ? ?',
    'Rare',
    138,
    false,
    'chars8x8rPets1'
  ],
  19471: [
    'Mini Desire Troll Skin',
    'Mini Desire Troll',
    2,
    '? ? ? ?',
    'Rare',
    139,
    false,
    'chars8x8rPets1'
  ],
  19474: ['Mini Rototo Skin', 'Mini Rototo', 3, '? ? ? ?', 'Rare', 140, false, 'chars8x8rPets1'],
  19477: [
    'Mini Flying Stheno Skin',
    'Mini Flying Stheno',
    1,
    'Reptile',
    'Rare',
    141,
    false,
    'chars8x8rPets1'
  ],
  19480: ['Surfing Bro Skin', 'Surfing Bro', 2, 'Humanoid', 'Divine', 39, false, 'petsDivine'],
  19503: [
    'Mini Ghost King Skin',
    'Mini Ghost King',
    2,
    'Spooky',
    'Rare',
    142,
    false,
    'chars8x8rPets1'
  ],
  19506: ['Robo Brain Skin', 'Robo Brain', null, 'Automaton', 'Rare', 143, false, 'chars8x8rPets1'],
  19509: [
    'Baby Orange Drake Skin',
    'Baby Orange Drake',
    1,
    'Reptile',
    'Rare',
    144,
    false,
    'chars8x8rPets1'
  ],
  19512: [
    'Baby Yellow Drake Skin',
    'Baby Yellow Drake',
    2,
    'Reptile',
    'Rare',
    145,
    false,
    'chars8x8rPets1'
  ],
  19515: [
    'Baby White Drake Skin',
    'Baby White Drake',
    null,
    'Reptile',
    'Rare',
    146,
    false,
    'chars8x8rPets1'
  ],
  19518: [
    'Baby Green Drake Skin',
    'Baby Green Drake',
    null,
    'Reptile',
    'Rare',
    147,
    false,
    'chars8x8rPets1'
  ],
  19521: [
    'Mini Leviathan Skin',
    'Mini Leviathan',
    3,
    'Reptile',
    'Rare',
    148,
    false,
    'chars8x8rPets1'
  ],
  19524: [
    'Baby Blue Drake Skin',
    'Baby Blue Drake',
    2,
    'Reptile',
    'Rare',
    149,
    false,
    'chars8x8rPets1'
  ],
  19527: [
    'Baby Purple Drake Skin',
    'Baby Purple Drake',
    2,
    'Reptile',
    'Rare',
    150,
    false,
    'chars8x8rPets1'
  ],
  19534: ['Pet HP Pot Skin', 'HP Pot Pet', 4, '? ? ? ?', 'Rare', 151, false, 'chars8x8rPets1'],
  19537: ['Pet MP Pot Skin', 'MP Pot Pet', 4, '? ? ? ?', 'Rare', 152, false, 'chars8x8rPets1'],
  19596: [
    'Crowned Penguin Skin',
    'Crowned Penguin',
    null,
    'Penguin',
    'Rare',
    153,
    false,
    'chars8x8rPets1'
  ],
  19599: [
    'Mini Void Entity Skin',
    'Mini Void Entity',
    4,
    'Spooky',
    'Rare',
    154,
    false,
    'chars8x8rPets1'
  ],
  19602: ['Hoverbot Skin', 'Hoverbot', 2, 'Automaton', 'Rare', 155, false, 'chars8x8rPets1'],
  19605: ['Zombie Dog Skin', 'Zombie Dog', 2, 'Canine', 'Rare', 156, false, 'chars8x8rPets1'],
  19608: ['Green Whale Skin', 'Green Whale', 3, 'Aquatic', 'Divine', 40, false, 'petsDivine'],
  19611: [
    "Pumpking's Head Skin",
    "Pumpking's Head",
    3,
    'Spooky',
    'Divine',
    41,
    false,
    'petsDivine'
  ],
  19626: ['Manticore Skin', 'Manticore', null, 'Feline', 'Divine', 42, false, 'petsDivine'],
  19629: ['Flying Pig Skin', 'Flying Pig', 3, 'Farm', 'Divine', 43, false, 'petsDivine'],
  19632: ['Double Viper Skin', 'Double Viper', null, 'Reptile', 'Divine', 44, false, 'petsDivine'],
  19635: [
    'Black Hellhound Skin',
    'Black Hellhound',
    4,
    'Canine',
    'Divine',
    45,
    false,
    'petsDivine'
  ],
  19638: ['Deerigator Skin', 'Deerigator', null, 'Reptile', 'Divine', 46, false, 'petsDivine'],
  19641: ['Moon Bunny Skin', 'Moon Bunny', 4, 'Farm', 'Rare', 157, false, 'chars8x8rPets1'],
  19644: [
    'Hungry Pumpkin Skin',
    'Hungry Pumpkin',
    3,
    'Spooky',
    'Rare',
    158,
    false,
    'chars8x8rPets1'
  ],
  19647: ['Evil Ghost Skin', 'Evil Ghost', 1, 'Spooky', 'Rare', 159, false, 'chars8x8rPets1'],
  19650: ['Spooky Boi Skin', 'Spooky Boi', 4, 'Spooky', 'Rare', 160, false, 'chars8x8rPets1'],
  19653: ['Walking Grave Skin', 'Walking Grave', 2, 'Spooky', 'Rare', 161, false, 'chars8x8rPets1'],
  21641: [
    'Enlightened Bookwyrm Pet Skin',
    'Cultured Bookwyrm',
    1,
    'Reptile',
    'Divine',
    7,
    true,
    'hauntedHallowsChars16x16'
  ],
  23309: ['Mini Lord Pet Skin', 'Mini Lord', 3, '? ? ? ?', 'Rare', 237, false, 'chars8x8rPets1'],
  23312: [
    'Mini Tornado Pet Skin',
    'Mini Tornado',
    3,
    '? ? ? ?',
    'Common',
    238,
    false,
    'chars8x8rPets1'
  ],
  23315: [
    'Wooden Burrito Pet Skin',
    'Wooden Burrito',
    2,
    '? ? ? ?',
    'Rare',
    239,
    false,
    'chars8x8rPets1'
  ],
  23318: ['Mini Nikao Pet Skin', 'Mini Nikao', 2, '? ? ? ?', 'Rare', 240, false, 'chars8x8rPets1'],
  23321: ["Lil' Davy Pet Skin", "Lil' Davy", 1, '? ? ? ?', 'Rare', 241, false, 'chars8x8rPets1'],
  23324: [
    'Maneki-neko Pet Skin',
    'Maneki-neko',
    null,
    'Feline',
    'Rare',
    244,
    false,
    'chars8x8rPets1'
  ],
  24603: [
    'King Skin of the Toys Skin',
    'King Skin of the Toys',
    3,
    '? ? ? ?',
    'Divine',
    50,
    false,
    'petsDivine'
  ],
  24606: [
    'Festive Slurp Skin',
    'Festive Slurp',
    1,
    'Aquatic',
    'Rare',
    170,
    false,
    'chars8x8rPets1'
  ],
  24610: [
    'Holiday Penguin Skin',
    'Holiday Penguin',
    2,
    'Penguin',
    'Rare',
    171,
    false,
    'chars8x8rPets1'
  ],
  24613: ['Young Elk Skin', 'Young Elk', 2, 'Woodland', 'Divine', 51, false, 'petsDivine'],
  24616: ['Krampus Skin', 'Krampus', 3, 'Spooky', 'Divine', 52, false, 'petsDivine'],
  24649: ['Egg Monster Skin', 'Egg Monster', null, 'Spooky', 'Rare', 53, false, 'petsDivine'],
  24652: ['Peacock Skin', 'Peacock', null, 'Avian', 'Divine', 54, false, 'petsDivine'],
  24655: [
    'Tricycle Bot Skin',
    'Tricycle Bot',
    2,
    'Automaton',
    'Rare',
    172,
    false,
    'chars8x8rPets1'
  ],
  24658: [
    'Mini Candy Gnome Skin',
    'Mini Candy Gnome',
    2,
    'Humanoid',
    'Rare',
    173,
    false,
    'chars8x8rPets1'
  ],
  24661: ["Lil' Mummy Skin", "Lil' Mummy", null, 'Spooky', 'Common', 174, false, 'chars8x8rPets1'],
  24664: [
    'Parasaurolophus Skin',
    'Parasaurolophus',
    3,
    'Reptile',
    'Divine',
    55,
    false,
    'petsDivine'
  ],
  24667: ['Lambeosaurus Skin', 'Lambeosaurus', 3, 'Reptile', 'Divine', 56, false, 'petsDivine'],
  24690: [
    'Guiding Spirit Skin',
    'Guiding Spirit',
    4,
    '? ? ? ?',
    'Rare',
    176,
    false,
    'chars8x8rPets1'
  ],
  24724: ['Red Heart Skin', 'Red Heart', 4, '? ? ? ?', 'Rare', 177, false, 'chars8x8rPets1'],
  24727: ['Pink Heart Skin', 'Pink Heart', null, '? ? ? ?', 'Rare', 178, false, 'chars8x8rPets1'],
  24730: ['Mini Pegasus Skin', 'Mini Pegasus', 2, 'Farm', 'Rare', 179, false, 'chars8x8rPets1'],
  24733: ['Prince Frog Skin', 'Prince Frog', 2, 'Aquatic', 'Rare', 180, false, 'chars8x8rPets1'],
  24836: ['Bagston Skin', 'Sir Bagston', 3, '? ? ? ?', 'Divine', 107, false, 'chars8x8rPets1'],
  24839: ['Goldy Skin', 'Goldy', 3, '? ? ? ?', 'Divine', 108, false, 'chars8x8rPets1'],
  24842: ['Jaco Skin', 'Jaco', 2, 'Spooky', 'Divine', 33, false, 'petsDivine'],
  25088: ['Lovebird Skin', 'Lovebird', 2, 'Avian', 'Rare', 182, false, 'chars8x8rPets1'],
  25091: ['Rat Skin', 'Rat', null, 'Woodland', 'Common', 183, false, 'chars8x8rPets1'],
  25094: ['Goldfish Skin', 'Goldfish', 2, 'Aquatic', 'Rare', 181, false, 'chars8x8rPets1'],
  25097: ['Giant Monarch Skin', 'Giant Monarch', null, 'Insect', 'Divine', 57, false, 'petsDivine'],
  25100: ['Zodiac Dog Skin', 'Zodiac Dog', null, 'Canine', 'Divine', 58, false, 'petsDivine'],
  25473: [
    'Swamped Panda Pet Skin',
    'Swamped Panda',
    4,
    'Exotic',
    'Divine',
    15,
    true,
    'wetlandsChars16x16'
  ],
  25609: [
    'World Turtles Pet Skin',
    'World Turtles',
    4,
    'Reptile',
    'Divine',
    81,
    false,
    'petsDivine'
  ],
  28813: ['Morpho Pet Skin', 'Morpho', 3, 'Insect', 'Rare', 220, false, 'chars8x8rPets1'],
  29345: [
    'Living Tree Pet Skin',
    'Living Tree',
    3,
    'Woodland',
    'Rare',
    224,
    false,
    'chars8x8rPets1'
  ],
  29348: ['Chinchilla Pet Skin', 'Chinchilla', 2, 'Exotic', 'Rare', 225, false, 'chars8x8rPets1'],
  29351: [
    'Golden Chess Piece Pet Skin',
    'Golden Chess Piece',
    3,
    '? ? ? ?',
    'Rare',
    226,
    false,
    'chars8x8rPets1'
  ],
  29354: ['Sprout Slime Pet Skin', 'Sprout Slime', 4, '? ? ? ?', 'Divine', 85, false, 'petsDivine'],
  30059: [
    'Ivory Narwhal Pet Skin',
    'Ivory Narwhal',
    4,
    'Aquatic',
    'Divine',
    92,
    false,
    'petsDivine'
  ],
  30062: ['Armored Orc Pet Skin', 'Armored Orc', 3, 'Humanoid', 'Divine', 93, false, 'petsDivine'],
  30065: [
    'Enchanted Broom Pet Skin',
    'Enchanted Broom',
    2,
    '? ? ? ?',
    'Divine',
    94,
    false,
    'petsDivine'
  ],
  30068: [
    'Hollow Wendigo Pet Skin',
    'Hollow Wendigo',
    4,
    'Spooky',
    'Divine',
    95,
    false,
    'petsDivine'
  ],
  30071: [
    'Tree Sparrow Pet Skin',
    'Tree Sparrow',
    3,
    'Avian',
    'Common',
    245,
    false,
    'chars8x8rPets1'
  ],
  30074: ['White Eyed Pet Skin', 'White Eyed', 2, 'Avian', 'Common', 246, false, 'chars8x8rPets1'],
  30077: ['Polar Bear Pet Skin', 'Polar Bear', 3, 'Exotic', 'Divine', 96, false, 'petsDivine'],
  30080: ['Snow Monster Pet Skin', 'Snow Monster', 4, 'Spooky', 'Divine', 97, false, 'petsDivine'],
  30083: [
    'Longtailed Tit Pet Skin',
    'Longtailed Tit',
    null,
    'Avian',
    'Common',
    247,
    false,
    'chars8x8rPets1'
  ],
  30086: ['Searing Soul Pet Skin', 'Searing Soul', 4, '? ? ? ?', 'Divine', 98, false, 'petsDivine'],
  30089: ['Zodiac Pig Pet Skin', 'Zodiac Pig', null, 'Farm', 'Divine', 99, false, 'petsDivine'],
  30103: ['Swan Pet Skin', 'Swan', 4, 'Farm', 'Divine', 100, false, 'petsDivine'],
  30106: [
    'Green Hat Bunny Pet Skin',
    'Green Hat Bunny',
    2,
    'Farm',
    'Rare',
    248,
    false,
    'chars8x8rPets1'
  ],
  30109: [
    'Cultured Bookwyrm Pet Skin',
    'Cultured Bookwyrm',
    1,
    'Reptile',
    'Divine',
    101,
    false,
    'petsDivine'
  ],
  30112: ['Mini Whale Pet Skin', 'Mini Whale', 2, 'Aquatic', 'Rare', 249, false, 'chars8x8rPets1'],
  30115: [
    'Champion Spirit Pet Skin',
    'Champion Spirit',
    4,
    'Spooky',
    'Divine',
    102,
    false,
    'petsDivine'
  ],
  30118: [
    'Vicious Phantom Pet Skin',
    'Vicious Phantom',
    3,
    'Spooky',
    'Divine',
    103,
    false,
    'petsDivine'
  ],
  30121: ['Toaster Pet Skin', 'Toaster', 3, '? ? ? ?', 'Divine', 104, false, 'petsDivine'],
  30124: [
    'Warrior Duck Pet Skin',
    'Warrior Duck',
    4,
    'Humanoid',
    'Divine',
    105,
    false,
    'petsDivine'
  ],
  30127: [
    'Infested Bagston Pet Skin',
    'Infested Bagston',
    4,
    '? ? ? ?',
    'Divine',
    106,
    false,
    'petsDivine'
  ],
  30130: [
    'Crystal Cobra Pet Skin',
    'Crystal Cobra',
    4,
    'Reptile',
    'Divine',
    107,
    false,
    'petsDivine'
  ],
  30133: [
    'Possessed Lantern Pet Skin',
    'Possessed Lantern',
    3,
    'Spooky',
    'Divine',
    108,
    false,
    'petsDivine'
  ],
  30136: [
    'Malogian Saucer Pet Skin',
    'Malogian Saucer',
    2,
    'Automaton',
    'Divine',
    109,
    false,
    'petsDivine'
  ],
  30139: [
    'Untarian Saucer Pet Skin',
    'Untarian Saucer',
    2,
    'Automaton',
    'Divine',
    110,
    false,
    'petsDivine'
  ],
  30142: [
    'Foraxian Saucer Pet Skin',
    'Foraxian Saucer',
    2,
    'Automaton',
    'Divine',
    111,
    false,
    'petsDivine'
  ],
  30145: [
    'Katalonian Saucer Pet Skin',
    'Katalonian Saucer',
    2,
    'Automaton',
    'Divine',
    112,
    false,
    'petsDivine'
  ],
  30148: [
    'Chill Chickey Pet Skin',
    'Chill Chickey',
    4,
    'Avian',
    'Divine',
    113,
    false,
    'petsDivine'
  ],
  30151: [
    'Sir Wumple Pet Skin',
    'Sir Wumple',
    null,
    'Humanoid',
    'Rare',
    250,
    false,
    'chars8x8rPets1'
  ],
  30154: ['Shiba Inu Pet Skin', 'Shiba Inu', 4, 'Canine', 'Rare', 251, false, 'chars8x8rPets1'],
  30157: [
    'Blue Turtle Shell Pet Skin',
    'Blue Turtle Shell',
    4,
    '? ? ? ?',
    'Divine',
    114,
    false,
    'petsDivine'
  ],
  30160: [
    'Green Turtle Shell Pet Skin',
    'Green Turtle Shell',
    3,
    '? ? ? ?',
    'Rare',
    252,
    false,
    'chars8x8rPets1'
  ],
  30163: [
    'Red Turtle Shell Pet Skin',
    'Red Turtle Shell',
    2,
    '? ? ? ?',
    'Rare',
    253,
    false,
    'chars8x8rPets1'
  ],
  30166: ['Skelephant Pet Skin', 'Skelephant', 3, 'Spooky', 'Divine', 115, false, 'petsDivine'],
  30169: [
    'Phantom Tea Set Pet Skin',
    'Phantom Tea Set',
    3,
    '? ? ? ?',
    'Divine',
    116,
    false,
    'petsDivine'
  ],
  30172: [
    "Fool's Penguin Pet Skin",
    "Fool's Penguin",
    3,
    'Penguin',
    'Divine',
    117,
    false,
    'petsDivine'
  ],
  30175: [
    'Phantom Ghost Pet Skin',
    'Phantom Ghost',
    4,
    'Humanoid',
    'Divine',
    118,
    false,
    'petsDivine'
  ],
  30178: ['UFO Bot Pet Skin', 'UFO Bot', 2, 'Automaton', 'Rare', 254, false, 'chars8x8rPets1'],
  30181: [
    'Cyberpenguin Pet Skin',
    'Cyberpenguin',
    2,
    'Penguin',
    'Divine',
    119,
    false,
    'petsDivine'
  ],
  30184: [
    'Blue Flaming Pumpkin Pet Skin',
    'Blue Flaming Pumpkin',
    3,
    'Spooky',
    'Divine',
    120,
    false,
    'petsDivine'
  ],
  30187: [
    'Orange Flaming Pumpkin Pet Skin',
    'Orange Flaming Pumpkin',
    4,
    'Spooky',
    'Divine',
    121,
    false,
    'petsDivine'
  ],
  30190: [
    'Flying Penguin Pet Skin',
    'Flying Penguin',
    3,
    'Penguin',
    'Rare',
    255,
    false,
    'chars8x8rPets1'
  ],
  30193: ['Fire Spirit Pet Skin', 'Fire Spirit', 4, '? ? ? ?', 'Divine', 122, false, 'petsDivine'],
  30196: [
    'Earth Spirit Pet Skin',
    'Earth Spirit',
    3,
    '? ? ? ?',
    'Divine',
    123,
    false,
    'petsDivine'
  ],
  30199: [
    'Water Spirit Pet Skin',
    'Water Spirit',
    3,
    '? ? ? ?',
    'Divine',
    124,
    false,
    'petsDivine'
  ],
  30202: [
    "Santa's Penguin Pet Skin",
    "Santa's Penguin",
    3,
    'Penguin',
    'Divine',
    125,
    false,
    'petsDivine'
  ],
  30208: [
    'Auroral Sprite God Pet Skin',
    'Auroral Sprite God',
    null,
    '? ? ? ?',
    'Divine',
    127,
    false,
    'petsDivine'
  ],
  30211: [
    'Cursed Blade Pet Skin',
    'Cursed Blade',
    4,
    '? ? ? ?',
    'Divine',
    128,
    false,
    'petsDivine'
  ],
  30214: [
    'Mini Marble Colossus Pet Skin',
    'Mini Marble Colossus',
    4,
    '? ? ? ?',
    'Rare',
    256,
    false,
    'chars8x8rPets1'
  ],
  30217: [
    'Majestic Moose Pet Skin',
    'Majestic Moose',
    4,
    'Woodland',
    'Divine',
    129,
    false,
    'petsDivine'
  ],
  30220: [
    'Winter Guide Pet Skin',
    'Winter Guide',
    4,
    'Humanoid',
    'Divine',
    130,
    false,
    'petsDivine'
  ],
  30223: ['Air Spirit Pet Skin', 'Air Spirit', 3, '? ? ? ?', 'Divine', 131, false, 'petsDivine'],
  30226: ['Zodiac Rat Pet Skin', 'Zodiac Rat', null, 'Farm', 'Divine', 132, false, 'petsDivine'],
  30229: [
    'Blessed Blade Pet Skin',
    'Blessed Blade',
    4,
    '? ? ? ?',
    'Divine',
    133,
    false,
    'petsDivine'
  ],
  30232: [
    'Suntanned Snowman Pet Skin',
    'Suntanned Snowman',
    2,
    '? ? ? ?',
    'Rare',
    257,
    false,
    'chars8x8rPets1'
  ],
  30235: ['Pet Wardrobe Pet Skin', 'Pet Wardrobe', 3, 'Spooky', 'Divine', 134, false, 'petsDivine'],
  30238: [
    'Compact Enforcer Pet Skin',
    'Compact Enforcer',
    2,
    'Automaton',
    'Divine',
    135,
    false,
    'petsDivine'
  ],
  30241: ['Ferret Pet Skin', 'Ferret', 2, 'Woodland', 'Divine', 136, false, 'petsDivine'],
  30244: ['Grub Pet Skin', 'Grub', 4, '? ? ? ?', 'Divine', 137, false, 'petsDivine'],
  30247: [
    'Ascended Guardian Pet Skin',
    'Ascended Guardian',
    4,
    'Penguin',
    'Divine',
    138,
    false,
    'petsDivine'
  ],
  30250: ['Music Box Pet Skin', 'Music Box', 2, '? ? ? ?', 'Divine', 139, false, 'petsDivine'],
  30253: ['Void Hound Pet Skin', 'Void Hound', 4, 'Canine', 'Divine', 140, false, 'petsDivine'],
  30256: [
    'Autumn Guide Pet Skin',
    'Autumn Guide',
    4,
    'Humanoid',
    'Divine',
    141,
    false,
    'petsDivine'
  ],
  30259: [
    'Time Traveling Phonebox Pet Skin',
    'Time Traveling Phonebox',
    3,
    '? ? ? ?',
    'Divine',
    142,
    false,
    'petsDivine'
  ],
  30262: [
    'Summer Guide Pet Skin',
    'Summer Guide',
    4,
    'Humanoid',
    'Divine',
    143,
    false,
    'petsDivine'
  ],
  30265: [
    'Old Nexus Orc Pet Skin',
    'Old Nexus Orc',
    4,
    'Humanoid',
    'Divine',
    144,
    false,
    'petsDivine'
  ],
  30268: ['TV Buddy Pet Skin', 'TV Buddy', 4, '? ? ? ?', 'Rare', 258, false, 'chars8x8rPets1'],
  30271: ['Demon Cat Pet Skin', 'Demon Cat', 3, 'Feline', 'Rare', 259, false, 'chars8x8rPets1'],
  30274: ['House Cat Pet Skin', 'House Cat', 4, 'Feline', 'Rare', 260, false, 'chars8x8rPets1'],
  30277: ['Husky Pet Skin', 'Husky', 3, 'Canine', 'Rare', 261, false, 'chars8x8rPets1'],
  30280: [
    'Floating Eye Bot Pet Skin',
    'Floating Eye Bot',
    3,
    'Automaton',
    'Divine',
    145,
    false,
    'petsDivine'
  ],
  30283: [
    'Enchanted Sea Turtle Pet Skin',
    'Enchanted Sea Turtle',
    4,
    'Aquatic',
    'Divine',
    146,
    false,
    'petsDivine'
  ],
  30286: ['Giant Worm Pet Skin', 'Giant Worm', 4, 'Insect', 'Divine', 147, false, 'petsDivine'],
  30289: [
    'Bulldozer Penguin Pet Skin',
    'Bulldozer Penguin',
    2,
    'Penguin',
    'Divine',
    148,
    false,
    'petsDivine'
  ],
  30292: [
    'Mobile Crane Penguin Pet Skin',
    'Mobile Crane Penguin',
    3,
    'Penguin',
    'Divine',
    149,
    false,
    'petsDivine'
  ],
  30295: [
    'Excavator Penguin Pet Skin',
    'Excavator Penguin',
    3,
    'Penguin',
    'Divine',
    150,
    false,
    'petsDivine'
  ],
  30298: [
    'Road Roller Penguin Pet Skin',
    'Road Roller Penguin',
    null,
    'Penguin',
    'Divine',
    151,
    false,
    'petsDivine'
  ],
  30301: [
    'Traffic Controller Penguin Pet Skin',
    'Traffic Controller Penguin',
    2,
    'Penguin',
    'Rare',
    262,
    false,
    'chars8x8rPets1'
  ],
  30304: [
    'Hungry Toolbox Pet Skin',
    'Hungry Toolbox',
    2,
    '? ? ? ?',
    'Rare',
    263,
    false,
    'chars8x8rPets1'
  ],
  30307: [
    'Janus the Fategazer Pet Skin',
    'Janus the Fategazer',
    null,
    '? ? ? ?',
    'Divine',
    152,
    false,
    'petsDivine'
  ],
  30310: [
    'Mini Guill Pet Skin',
    'Mini Guill',
    null,
    'Humanoid',
    'Rare',
    264,
    false,
    'chars8x8rPets1'
  ],
  30313: [
    'Nexus Sheep Pet Skin',
    'Nexus Sheep',
    null,
    'Farm',
    'Rare',
    265,
    false,
    'chars8x8rPets1'
  ],
  30316: [
    'Stone Brothers Pet Skin',
    'Stone Brothers',
    null,
    'Humanoid',
    'Divine',
    153,
    false,
    'petsDivine'
  ],
  30319: [
    'Oryx the Exalted Pet Skin',
    'Oryx the Exalted',
    null,
    '? ? ? ?',
    'Divine',
    23,
    false,
    'oryxSanctuaryChars32x32'
  ],
  30322: [
    'Sapling Buddy Pet Skin',
    'Sapling Buddy',
    2,
    'Woodland',
    'Rare',
    266,
    false,
    'chars8x8rPets1'
  ],
  30325: [
    'Scallywag Slurp Pet Skin',
    'Scallywag Slurp',
    2,
    'Aquatic',
    'Rare',
    267,
    false,
    'chars8x8rPets1'
  ],
  30328: [
    'Baby Basilisk Pet Skin',
    'Baby Basilisk',
    2,
    'Reptile',
    'Rare',
    268,
    false,
    'chars8x8rPets1'
  ],
  30331: ['Horned Wyrm Pet Skin', 'Horned Wyrm', 2, 'Reptile', 'Divine', 154, false, 'petsDivine'],
  30334: [
    'Possessed Staff Pet Skin',
    'Possessed Staff',
    2,
    '? ? ? ?',
    'Divine',
    155,
    false,
    'petsDivine'
  ],
  30337: [
    'Eggshell Spider Pet Skin',
    'Eggshell Spider',
    2,
    'Insect',
    'Rare',
    269,
    false,
    'chars8x8rPets1'
  ],
  30340: ['Blizzard Pet Skin', 'Blizzard', 2, 'Feline', 'Divine', 156, false, 'petsDivine'],
  30343: [
    'Fiery Phylactery Pet Skin',
    'Fiery Phylactery',
    1,
    'Spooky',
    'Divine',
    157,
    false,
    'petsDivine'
  ],
  30346: [
    'Giant Zombie Feet Pet Skin',
    'Giant Zombie Feet',
    2,
    'Spooky',
    'Divine',
    158,
    false,
    'petsDivine'
  ],
  30349: [
    'Skeleton Drake Pet Skin',
    'Skeleton Drake',
    2,
    'Reptile',
    'Divine',
    159,
    false,
    'petsDivine'
  ],
  30352: [
    'Zombie Drake Pet Skin',
    'Zombie Drake',
    2,
    'Reptile',
    'Divine',
    160,
    false,
    'petsDivine'
  ],
  30355: [
    'Witch Hat Rat Pet Skin',
    'Witch Hat Rat',
    3,
    'Spooky',
    'Divine',
    161,
    false,
    'petsDivine'
  ],
  30358: [
    'Spectral Skeledragon Pet Skin',
    'Spectral Skeledragon',
    3,
    'Spooky',
    'Divine',
    162,
    false,
    'petsDivine'
  ],
  30361: [
    'King Rarthur Pet Skin',
    'King Rarthur',
    2,
    'Woodland',
    'Divine',
    163,
    false,
    'petsDivine'
  ],
  30364: [
    'Red-Nosed Friend Pet Skin',
    'Red-Nosed Friend',
    3,
    'Woodland',
    'Rare',
    270,
    false,
    'chars8x8rPets1'
  ],
  30367: [
    'Mouse Prince Pet Skin',
    'Mouse Prince',
    2,
    'Woodland',
    'Rare',
    271,
    false,
    'chars8x8rPets1'
  ],
  30370: [
    'Aerodynamical Penguin Pet Skin',
    'Aerodynamical Penguin',
    4,
    'Penguin',
    'Divine',
    164,
    false,
    'petsDivine'
  ],
  30373: ['Big Pingus Pet Skin', 'Big Pingus', 4, 'Penguin', 'Divine', 165, false, 'petsDivine'],
  30376: ['Zodiac Ox Pet Skin', 'Zodiac Ox', null, 'Farm', 'Divine', 166, false, 'petsDivine'],
  30379: [
    "Mini 'Odonna Pet Skin",
    "Mini 'Odonna",
    3,
    '? ? ? ?',
    'Rare',
    272,
    false,
    'chars8x8rPets1'
  ],
  30382: [
    "Lil' Forest Harpy Pet Skin",
    "Lil' Forest Harpy",
    2,
    'Humanoid',
    'Rare',
    273,
    false,
    'chars8x8rPets1'
  ],
  30385: [
    'Valentine Cupcake Pet Skin',
    'Valentine Cupcake',
    3,
    '? ? ? ?',
    'Divine',
    167,
    false,
    'petsDivine'
  ],
  30388: ['Lovey Teddy Pet Skin', 'Lovey Teddy', 3, '? ? ? ?', 'Divine', 168, false, 'petsDivine'],
  30391: [
    'Android Companion Pet Skin',
    'Android Companion',
    3,
    'Automaton',
    'Divine',
    169,
    false,
    'petsDivine'
  ],
  30394: [
    'Nightray Pegasus Pet Skin',
    'Nightray Pegasus',
    4,
    'Farm',
    'Divine',
    170,
    false,
    'petsDivine'
  ],
  30397: [
    'Glorious Pegasus Pet Skin',
    'Glorious Pegasus',
    4,
    'Farm',
    'Divine',
    171,
    false,
    'petsDivine'
  ],
  30400: [
    'Forest Harpy Pet Skin',
    'Forest Harpy',
    4,
    'Humanoid',
    'Divine',
    172,
    false,
    'petsDivine'
  ],
  30403: [
    'Helicopter Penguin Pet Skin',
    'Helicopter Penguin',
    4,
    'Penguin',
    'Divine',
    173,
    false,
    'petsDivine'
  ],
  30406: [
    'Infernal Archdragon Pet Skin',
    'Infernal Archdragon',
    4,
    'Reptile',
    'Divine',
    174,
    false,
    'petsDivine'
  ],
  30409: ['Sakura Deer Pet Skin', 'Sakura Deer', 4, 'Woodland', 'Divine', 175, false, 'petsDivine'],
  30412: [
    'Lucky Fourleaf Pet Skin',
    'Lucky Fourleaf',
    4,
    'Woodland',
    'Divine',
    176,
    false,
    'petsDivine'
  ],
  30415: [
    'Golden Lucky Fourleaf Pet Skin',
    'Lucky Fourleaf',
    4,
    'Woodland',
    'Divine',
    177,
    false,
    'petsDivine'
  ],
  30418: [
    'Chocolate Bunny Pet Skin',
    'Chocolate Bunny',
    3,
    'Farm',
    'Rare',
    274,
    false,
    'chars8x8rPets1'
  ],
  30421: [
    'Battlebot MK1 Pet Skin',
    'Battlebot MK1',
    2,
    'Automaton',
    'Divine',
    178,
    false,
    'petsDivine'
  ],
  30424: [
    'Mystery Rare Pet Skin',
    'Mystery Rare Pet',
    null,
    '? ? ? ?',
    'Rare',
    275,
    false,
    'chars8x8rPets1'
  ],
  30427: [
    'Mystery Epic Pet Skin',
    'Mystery Epic Pet',
    null,
    '? ? ? ?',
    'Rare',
    276,
    false,
    'chars8x8rPets1'
  ],
  30430: [
    'Mystery Legendary Pet Skin',
    'Mystery Legendary Pet',
    null,
    '? ? ? ?',
    'Rare',
    277,
    false,
    'chars8x8rPets1'
  ],
  30433: [
    'Easter Island Head Pet Skin',
    'Easter Island Head',
    4,
    '? ? ? ?',
    'Divine',
    179,
    false,
    'petsDivine'
  ],
  30436: ['Gazelle Pet Skin', 'Gazelle', 4, 'Exotic', 'Divine', 180, false, 'petsDivine'],
  30439: [
    'Crystal Pony Pet Skin',
    'Crystal Pony',
    null,
    '? ? ? ?',
    'Rare',
    278,
    false,
    'chars8x8rPets1'
  ],
  30442: [
    'Son of the Son of Arachna Pet Skin',
    'Son of the Son of Arachna',
    null,
    'Insect',
    'Rare',
    279,
    false,
    'chars8x8rPets1'
  ],
  30445: [
    'Calamity Crab Pet Skin',
    'Calamity Crab',
    null,
    'Aquatic',
    'Divine',
    8,
    true,
    'deadwaterDocksChars16x16'
  ],
  30449: ['Bananalien Pet Skin', 'Bananalien', 4, '? ? ? ?', 'Divine', 181, false, 'petsDivine'],
  30452: ['Egg-bot Pet Skin', 'Egg-bot', null, 'Automaton', 'Divine', 182, false, 'petsDivine'],
  30455: ['Malus? Pet Skin', 'Malus?', 4, 'Humanoid', 'Divine', 183, false, 'petsDivine'],
  30458: ['Biard Pet Skin', 'Biard', 3, 'Avian', 'Divine', 184, false, 'petsDivine'],
  30461: [
    'Oryx the Baby God Pet Skin',
    'Oryx the Baby God',
    4,
    'Humanoid',
    'Rare',
    281,
    false,
    'chars8x8rPets1'
  ],
  30464: [
    'Sol the Energy Drink Pet Skin',
    'Sol the Energy Drink',
    1,
    '? ? ? ?',
    'Divine',
    185,
    false,
    'petsDivine'
  ],
  30467: [
    'Skulking Skull King Pet Skin',
    'Skulking Skull King',
    null,
    'Spooky',
    'Divine',
    186,
    false,
    'petsDivine'
  ],
  30470: ['Octopus Pet Skin', 'Octopus', 4, 'Aquatic', 'Divine', 187, false, 'petsDivine'],
  30473: [
    'Snail of the Juggernaut Pet Skin',
    'Snail of the Juggernaut',
    4,
    'Aquatic',
    'Rare',
    282,
    false,
    'chars8x8rPets1'
  ],
  30476: [
    'Fallen Protector Pet Skin',
    'Fallen Protector',
    4,
    'Humanoid',
    'Divine',
    188,
    false,
    'petsDivine'
  ],
  30479: [
    'Redeemed Void Shade Pet Skin',
    'Redeemed Void Shade',
    3,
    'Humanoid',
    'Divine',
    189,
    false,
    'petsDivine'
  ],
  30482: ['Duality Pet Skin', 'Duality', 4, '? ? ? ?', 'Divine', 190, false, 'petsDivine'],
  30485: ['Daeva Oryx Pet Skin', 'Daeva Oryx', 4, 'Humanoid', 'Divine', 191, false, 'petsDivine'],
  30488: ['Seraphim Pet Skin', 'Seraphim', 4, '? ? ? ?', 'Divine', 192, false, 'petsDivine'],
  30491: ['Voided Oryx Pet Skin', 'Voided Oryx', 4, 'Humanoid', 'Divine', 193, false, 'petsDivine'],
  30494: [
    'Corrupted Tinkerer Pet Skin',
    'Corrupted Tinkerer',
    2,
    'Humanoid',
    'Rare',
    283,
    false,
    'chars8x8rPets1'
  ],
  30497: [
    'Corrupted Login Seer Pet Skin',
    'Corrupted Login Seer',
    1,
    'Humanoid',
    'Rare',
    284,
    false,
    'chars8x8rPets1'
  ],
  30500: [
    "Lil' Ice Cream Pet Skin",
    "Lil' Ice Cream",
    2,
    '? ? ? ?',
    'Rare',
    285,
    false,
    'chars8x8rPets1'
  ],
  30503: [
    'Fizzy Drink Pet Skin',
    'Fizzy Drink',
    2,
    '? ? ? ?',
    'Rare',
    286,
    false,
    'chars8x8rPets1'
  ],
  30506: [
    'Cured Tinkerer Pet Skin',
    'Cured Tinkerer',
    1,
    'Humanoid',
    'Rare',
    287,
    false,
    'chars8x8rPets1'
  ],
  30509: [
    'Cured Login Seer Pet Skin',
    'Cured Login Seer',
    1,
    'Humanoid',
    'Rare',
    288,
    false,
    'chars8x8rPets1'
  ],
  30512: [
    'Eye of the Void Pet Skin',
    'Eye of the Void',
    null,
    'Spooky',
    'Rare',
    289,
    false,
    'chars8x8rPets1'
  ],
  30515: [
    'Celestial Construct Pet Skin',
    'Celestial Construct',
    null,
    'Automaton',
    'Rare',
    290,
    false,
    'chars8x8rPets1'
  ],
  30518: [
    "Lil' Dark Ambrosia Pet Skin",
    "Lil' Dark Ambrosia",
    1,
    '? ? ? ?',
    'Rare',
    291,
    false,
    'chars8x8rPets1'
  ],
  30521: [
    'Corrupted Watering Can Pet Skin',
    'Corrupted Watering Can',
    1,
    '? ? ? ?',
    'Divine',
    194,
    false,
    'petsDivine'
  ],
  30524: [
    'Corrupted Penguin Explorer Pet Skin',
    'Corrupted Penguin Explorer',
    3,
    'Penguin',
    'Divine',
    195,
    false,
    'petsDivine'
  ],
  30527: [
    'Void Cleanser Penguin Pet Skin',
    'Void Cleanser Penguin',
    3,
    'Penguin',
    'Divine',
    196,
    false,
    'petsDivine'
  ],
  30530: [
    'Sentinel Watchdog Pet Skin',
    'Sentinel Watchdog',
    2,
    'Canine',
    'Divine',
    197,
    false,
    'petsDivine'
  ],
  30533: [
    'Shadow Stormbird Pet Skin',
    'Shadow Stormbird',
    2,
    'Avian',
    'Divine',
    198,
    false,
    'petsDivine'
  ],
  30536: [
    'Royal Void Cat Pet Skin',
    'Royal Void Cat',
    2,
    'Feline',
    'Divine',
    199,
    false,
    'petsDivine'
  ],
  30539: [
    "Lil' Keyper Pet Skin",
    "Lil' Keyper",
    2,
    'Humanoid',
    'Rare',
    292,
    false,
    'chars8x8rPets1'
  ],
  30542: [
    'Angelic Blossom Pet Skin',
    'Angelic Blossom',
    2,
    '? ? ? ?',
    'Rare',
    293,
    false,
    'chars8x8rPets1'
  ],
  30545: [
    'Nurse Wheelie Pet Skin',
    'Nurse Wheelie',
    4,
    'Automaton',
    'Divine',
    200,
    false,
    'petsDivine'
  ],
  30548: [
    'Sphenisciform Entity Pet Skin',
    'Sphenisciform Entity',
    null,
    'Penguin',
    'Divine',
    201,
    false,
    'petsDivine'
  ],
  30551: [
    'Cherubic Penguin Pet Skin',
    'Cherubic Penguin',
    null,
    'Penguin',
    'Divine',
    202,
    false,
    'petsDivine'
  ],
  30554: ['Graylien Pet Skin', 'Graylien', 4, '? ? ? ?', 'Divine', 203, false, 'petsDivine'],
  30557: ['Carnage Cat Pet Skin', 'Carnage Cat', 2, 'Feline', 'Rare', 294, false, 'chars8x8rPets1'],
  30560: [
    "Lil' Backpack Pet Skin",
    "Lil' Backpack",
    4,
    '? ? ? ?',
    'Divine',
    204,
    false,
    'petsDivine'
  ],
  30563: ['Clipboard Pet Skin', 'Clipboard', 2, '? ? ? ?', 'Divine', 205, false, 'petsDivine'],
  30566: [
    'Floating Beer Pet Skin',
    'Floating Beer',
    2,
    '? ? ? ?',
    'Divine',
    206,
    false,
    'petsDivine'
  ],
  30569: [
    'Garlic Buddy Pet Skin',
    'Garlic Buddy',
    4,
    '? ? ? ?',
    'Divine',
    207,
    false,
    'petsDivine'
  ],
  30571: [
    'Golden Pet Rock Skin',
    'Golden Pet Rock',
    null,
    '? ? ? ?',
    'Divine',
    256,
    false,
    'petsDivine'
  ],
  30578: ['Spectral Bat Pet Skin', 'Spectral Bat', 2, 'Spooky', 'Divine', 208, false, 'petsDivine'],
  30581: [
    'Ghastly Penguin Pet Skin',
    'Ghastly Penguin',
    4,
    'Penguin',
    'Divine',
    209,
    false,
    'petsDivine'
  ],
  30584: [
    'Cursed Portrait Pet Skin',
    'Cursed Portrait',
    3,
    'Spooky',
    'Divine',
    210,
    false,
    'petsDivine'
  ],
  30587: [
    'Bloodthirsty Penguin Pet Skin',
    'Bloodthirsty Penguin',
    2,
    'Penguin',
    'Divine',
    211,
    false,
    'petsDivine'
  ],
  30611: [
    'Eldritch Clown Pet Skin',
    'Eldritch Clown',
    4,
    'Spooky',
    'Divine',
    212,
    false,
    'petsDivine'
  ],
  30614: ['Campfire Pet Skin', 'Campfire', 3, '? ? ? ?', 'Divine', 213, false, 'petsDivine'],
  30977: [
    'George the Turkey Pet Skin',
    'George the Turkey',
    4,
    'Farm',
    'Divine',
    214,
    false,
    'petsDivine'
  ],
  30980: [
    'Snowplow Penguin Pet Skin',
    'Snowplow Penguin',
    3,
    'Penguin',
    'Divine',
    215,
    false,
    'petsDivine'
  ],
  30983: [
    'Movement Detector Doll Pet Skin',
    'Movement Detector Doll',
    4,
    'Automaton',
    'Divine',
    216,
    false,
    'petsDivine'
  ],
  30986: [
    'Festive Sprite Pet Skin',
    'Festive Sprite',
    4,
    '? ? ? ?',
    'Rare',
    295,
    false,
    'chars8x8rPets1'
  ],
  30989: [
    'Oryxmas Shiba Pet Skin',
    'Oryxmas Shiba',
    3,
    'Canine',
    'Rare',
    296,
    false,
    'chars8x8rPets1'
  ],
  30992: [
    'Gift-wrapped Box Pet Skin',
    'Gift-wrapped Box',
    5,
    'Feline',
    'Divine',
    217,
    false,
    'petsDivine'
  ],
  30995: [
    'Demon Mistress Pet Skin',
    'Demon Mistress',
    4,
    'Humanoid',
    'Divine',
    218,
    false,
    'petsDivine'
  ],
  30998: [
    'Ice Skating Penguin Pet Skin',
    'Ice Skating Penguin',
    5,
    'Penguin',
    'Divine',
    219,
    false,
    'petsDivine'
  ],
  31001: [
    'Oryxmas Tanuki Pet Skin',
    'Oryxmas Tanuki',
    3,
    'Canine',
    'Rare',
    297,
    false,
    'chars8x8rPets1'
  ],
  31004: ['Yau Gok Pet Skin', 'Yau Gok', 3, '? ? ? ?', 'Rare', 298, false, 'chars8x8rPets1'],
  31007: [
    'Bouncy Companion Pet Skin',
    'Bouncy Companion',
    2,
    '? ? ? ?',
    'Rare',
    299,
    false,
    'chars8x8rPets1'
  ],
  31010: [
    'Leprechaun Penguin Pet Skin',
    'Leprechaun Penguin',
    3,
    'Penguin',
    'Rare',
    300,
    false,
    'chars8x8rPets1'
  ],
  31013: [
    'Young Water Elemental Pet Skin',
    'Young Water Elemental',
    4,
    '? ? ? ?',
    'Rare',
    301,
    false,
    'chars8x8rPets1'
  ],
  31016: [
    'Young Earth Elemental Pet Skin',
    'Young Earth Elemental',
    4,
    '? ? ? ?',
    'Rare',
    302,
    false,
    'chars8x8rPets1'
  ],
  31019: [
    'Playful Bunny Pet Skin',
    'Playful Bunny',
    4,
    'Humanoid',
    'Rare',
    220,
    false,
    'petsDivine'
  ],
  31022: [
    'Young Fire Elemental Pet Skin',
    'Young Fire Elemental',
    5,
    '? ? ? ?',
    'Rare',
    221,
    false,
    'petsDivine'
  ],
  31025: [
    'Young Air Elemental Pet Skin',
    'Young Air Elemental',
    3,
    '? ? ? ?',
    'Rare',
    303,
    false,
    'chars8x8rPets1'
  ],
  31028: [
    'Perception of Guill Pet Skin',
    'Perception of Guill',
    null,
    'Humanoid',
    'Rare',
    222,
    false,
    'petsDivine'
  ],
  31031: [
    'Elemental Beast Pet Skin',
    'Elemental Beast',
    6,
    'Canine',
    'Divine',
    223,
    false,
    'petsDivine'
  ],
  31034: [
    "Lil' Deep Sea Diva Pet Skin",
    "Lil' Deep Sea Diva",
    null,
    'Aquatic',
    'Rare',
    304,
    false,
    'chars8x8rPets1'
  ],
  31037: [
    "Lil' Mister Backstage Pet Skin",
    "Lil' Mister Backstage",
    null,
    'Humanoid',
    'Rare',
    305,
    false,
    'chars8x8rPets1'
  ],
  31040: [
    "Lil' Rad Raver Pet Skin",
    "Lil' Rad Raver",
    null,
    'Aquatic',
    'Rare',
    306,
    false,
    'chars8x8rPets1'
  ],
  31043: [
    "Lil' Thunderbringer Pet Skin",
    "Lil' Thunderbringer",
    null,
    'Humanoid',
    'Rare',
    307,
    false,
    'chars8x8rPets1'
  ],
  31058: [
    'Deep Sea Diva Action Figure Pet Skin',
    'Deep Sea Diva Action Figure',
    null,
    'Aquatic',
    'Divine',
    112,
    true,
    'chars16x16dEncounters2'
  ],
  31061: [
    'Mister Backstage Action Figure Pet Skin',
    'Mister Backstage Action Figure',
    null,
    'Humanoid',
    'Divine',
    110,
    true,
    'chars16x16dEncounters2'
  ],
  31064: [
    'Rad Raver Action Figure Pet Skin',
    'Rad Raver Action Figure',
    null,
    'Aquatic',
    'Divine',
    111,
    true,
    'chars16x16dEncounters2'
  ],
  31067: [
    'The Thunderbringer Action Figure Pet Skin',
    'The Thunderbringer Action Figure',
    null,
    'Humanoid',
    'Divine',
    114,
    true,
    'chars16x16dEncounters2'
  ],
  31070: ['White Husky Pet Skin', 'White Husky', 2, 'Canine', 'Divine', 224, false, 'petsDivine'],
  31073: ['Arctic Fox Pet Skin', 'Arctic Fox', 4, 'Canine', 'Divine', 225, false, 'petsDivine'],
  31076: [
    'Penguin Gunslinger Pet Skin',
    'Penguin Gunslinger',
    5,
    'Penguin',
    'Divine',
    226,
    false,
    'petsDivine'
  ],
  31079: [
    'Dimensional Wanderer Pet Skin',
    'Dimensional Wanderer',
    5,
    'Humanoid',
    'Divine',
    227,
    false,
    'petsDivine'
  ],
  31082: [
    'Syndicate Hellhound Pet Skin',
    'Syndicate Hellhound',
    5,
    'Canine',
    'Divine',
    228,
    false,
    'petsDivine'
  ],
  31085: ['Voodoo Doll Pet Skin', 'Voodoo Doll', 4, 'Spooky', 'Divine', 229, false, 'petsDivine'],
  31088: ['Voodoo Bat Pet Skin', 'Voodoo Bat', 5, 'Spooky', 'Divine', 230, false, 'petsDivine'],
  31091: [
    'Chibi Bridge Sentinel Pet Skin',
    'Chibi Bridge Sentinel',
    4,
    'Humanoid',
    'Divine',
    231,
    false,
    'petsDivine'
  ],
  31094: [
    'Chibi Twilight Archmage Pet Skin',
    'Chibi Twilight Archmage',
    4,
    'Humanoid',
    'Divine',
    232,
    false,
    'petsDivine'
  ],
  31101: [
    'Chibi Forgotten King Pet Skin',
    'Chibi Forgotten King',
    4,
    'Humanoid',
    'Divine',
    233,
    false,
    'petsDivine'
  ],
  31106: ['Chibi Oryx Pet Skin', 'Chibi Oryx', 4, 'Humanoid', 'Divine', 234, false, 'petsDivine'],
  31109: [
    'Chibi Heart of the Wetlands Pet Skin',
    'Chibi Heart of the Wetlands',
    4,
    'Woodland',
    'Divine',
    235,
    false,
    'petsDivine'
  ],
  31116: [
    'Mechanical Dog Pet Skin',
    'Mechanical Dog',
    5,
    'Canine',
    'Divine',
    236,
    false,
    'petsDivine'
  ],
  31119: [
    'Steampunk Cat Pet Skin',
    'Steampunk Cat',
    4,
    'Feline',
    'Divine',
    237,
    false,
    'petsDivine'
  ],
  32515: ['Autumn Ent Pet Skin', 'Autumn Ent', 3, 'Woodland', 'Divine', 91, false, 'petsDivine'],
  32652: ['Pumpkin Head Skin', 'Pumpkin Head', 2, 'Spooky', 'Divine', 109, false, 'chars8x8rPets1'],
  32669: [
    'Christmas Tree Skin',
    'Christmas Tree',
    null,
    '? ? ? ?',
    'Divine',
    110,
    false,
    'chars8x8rPets1'
  ],
  32671: ['Red Nose Skin', 'Red Nosed', 1, 'Woodland', 'Divine', 111, false, 'chars8x8rPets1'],
  32704: [
    'Red Bagston Skin',
    'Red Bagston',
    null,
    '? ? ? ?',
    'Divine',
    116,
    false,
    'chars8x8rPets1'
  ],
  32707: [
    'Helper Bagston Skin',
    'Helper Bagston',
    null,
    '? ? ? ?',
    'Divine',
    115,
    false,
    'chars8x8rPets1'
  ],
  32710: [
    'Red Helper Bagston Skin',
    'Red Helper Bagston',
    null,
    '? ? ? ?',
    'Divine',
    113,
    false,
    'chars8x8rPets1'
  ],
  32717: [
    'Muddy Tidechaser Skin',
    'Muddy Tidechaser',
    null,
    'Humanoid',
    'Common',
    117,
    false,
    'chars8x8rPets1'
  ],
  32764: [
    'Giant Vampire Bat Skin',
    'Giant Vampire Bat',
    1,
    'Spooky',
    'Divine',
    34,
    false,
    'petsDivine'
  ],
  32768: ['Black Cat Skin', 'Black Cat', null, 'Feline', 'Common', 0, false, 'chars8x8rPets1'],
  32769: ['Grey Cat Skin', 'Grey Cat', null, 'Feline', 'Common', 1, false, 'chars8x8rPets1'],
  32770: ['Orange Cat Skin', 'Orange Cat', null, 'Feline', 'Common', 2, false, 'chars8x8rPets1'],
  32771: ['Tan Cat Skin', 'Tan Cat', null, 'Feline', 'Common', 90, false, 'chars8x8rPets1'],
  32772: ['Yellow Cat Skin', 'Yellow Cat', null, 'Feline', 'Common', 92, false, 'chars8x8rPets1'],
  32773: ['White Cat Skin', 'White Cat', null, 'Feline', 'Common', 91, false, 'chars8x8rPets1'],
  32774: ['Brown Pup Skin', 'Brown Pup', null, 'Canine', 'Common', 5, false, 'chars8x8rPets1'],
  32775: ['Grey Pup Skin', 'Grey Pup', null, 'Canine', 'Common', 93, false, 'chars8x8rPets1'],
  32776: ['Golden Pup Skin', 'Golden Pup', null, 'Canine', 'Common', 94, false, 'chars8x8rPets1'],
  32777: ['Grey Wolf Skin', 'Grey Wolf', null, 'Canine', 'Common', 4, false, 'chars8x8rPets1'],
  32778: ['Brown Fox Skin', 'Brown Fox', null, 'Canine', 'Common', 6, false, 'chars8x8rPets1'],
  32779: ['Sheepdog Skin', 'Sheepdog', null, 'Canine', 'Common', 10, false, 'chars8x8rPets1'],
  32780: ['Grey Fox Skin', 'Grey Fox', null, 'Canine', 'Common', 95, false, 'chars8x8rPets1'],
  32781: ['Blue Parrot Skin', 'Blue Parrot', null, 'Avian', 'Common', 12, false, 'chars8x8rPets1'],
  32782: ['Oriole Skin', 'Oriole', null, 'Avian', 'Common', 59, false, 'chars8x8rPets1'],
  32783: ['Goldfinch Skin', 'Goldfinch', null, 'Avian', 'Common', 60, false, 'chars8x8rPets1'],
  32784: ['Bluebird Skin', 'Bluebird', null, 'Avian', 'Common', 61, false, 'chars8x8rPets1'],
  32785: ['Cardinal Skin', 'Cardinal', null, 'Avian', 'Common', 62, false, 'chars8x8rPets1'],
  32786: ['Elephant Skin', 'Elephant', null, 'Exotic', 'Common', 35, false, 'chars8x8rPets1'],
  32787: ['Koala Skin', 'Koala', null, 'Exotic', 'Common', 70, false, 'chars8x8rPets1'],
  32788: ['Monkey Skin', 'Monkey', null, 'Exotic', 'Common', 74, false, 'chars8x8rPets1'],
  32789: ['Chick Skin', 'Chick', null, 'Farm', 'Common', 13, false, 'chars8x8rPets1'],
  32790: ['Pig Skin', 'Pig', null, 'Farm', 'Common', 14, false, 'chars8x8rPets1'],
  32791: ['Duck Skin', 'Duck', null, 'Farm', 'Common', 22, false, 'chars8x8rPets1'],
  32792: ['Squirrel Skin', 'Squirrel', null, 'Woodland', 'Common', 18, false, 'chars8x8rPets1'],
  32793: ['Hamster Skin', 'Hamster', null, 'Woodland', 'Common', 33, false, 'chars8x8rPets1'],
  32794: ['Raccoon Skin', 'Raccoon', null, 'Woodland', 'Common', 75, false, 'chars8x8rPets1'],
  32795: ['Dino Skin', 'Dino', null, 'Reptile', 'Common', 34, false, 'chars8x8rPets1'],
  32796: ['Tomb Snake Skin', 'Tomb Snake', null, 'Reptile', 'Common', 64, false, 'chars8x8rPets1'],
  32797: ['Chameleon Skin', 'Chameleon', null, 'Reptile', 'Common', 76, false, 'chars8x8rPets1'],
  32798: ['Dragonfly Skin', 'Dragonfly', null, 'Insect', 'Common', 39, false, 'chars8x8rPets1'],
  32799: ['Black Ant Skin', 'Black Ant', null, 'Insect', 'Common', 53, false, 'chars8x8rPets1'],
  32800: ['Blue Ant Skin', 'Blue Ant', null, 'Insect', 'Common', 54, false, 'chars8x8rPets1'],
  32801: ['Green Ant Skin', 'Green Ant', null, 'Insect', 'Common', 55, false, 'chars8x8rPets1'],
  32802: ['Red Ant Skin', 'Red Ant', null, 'Insect', 'Common', 56, false, 'chars8x8rPets1'],
  32803: ['Purple Ant Skin', 'Purple Ant', null, 'Insect', 'Common', 57, false, 'chars8x8rPets1'],
  32804: ['Penguin Skin', 'Penguin', null, 'Penguin', 'Common', 9, false, 'chars8x8rPets1'],
  32805: [
    'Green Penguin Skin',
    'Green Penguin',
    null,
    'Penguin',
    'Common',
    96,
    false,
    'chars8x8rPets1'
  ],
  32806: [
    'Grape Penguin Skin',
    'Grape Penguin',
    null,
    'Penguin',
    'Common',
    29,
    false,
    'chars8x8rPets1'
  ],
  32807: [
    'Grass Penguin Skin',
    'Grass Penguin',
    null,
    'Penguin',
    'Common',
    30,
    false,
    'chars8x8rPets1'
  ],
  32808: ['Blue Snail Skin', 'Blue Snail', null, 'Aquatic', 'Common', 3, false, 'chars8x8rPets1'],
  32809: ['Green Frog Skin', 'Green Frog', null, 'Aquatic', 'Common', 7, false, 'chars8x8rPets1'],
  32810: [
    'Purple Snail Skin',
    'Purple Snail',
    null,
    'Aquatic',
    'Common',
    97,
    false,
    'chars8x8rPets1'
  ],
  32811: [
    'Purple Frog Skin',
    'Purple Frog',
    null,
    'Aquatic',
    'Common',
    98,
    false,
    'chars8x8rPets1'
  ],
  32812: ['Sea Slurp Skin', 'Sea Slurp', null, 'Aquatic', 'Common', 15, false, 'chars8x8rPets1'],
  32813: ['Turtle Skin', 'Turtle', null, 'Aquatic', 'Common', 24, false, 'chars8x8rPets1'],
  32814: ['Crab Skin', 'Crab', null, 'Aquatic', 'Common', 32, false, 'chars8x8rPets1'],
  32816: ['Bat Skin', 'Bat', null, 'Spooky', 'Common', 103, false, 'chars8x8rPets1'],
  32817: ["Lil' Ghost Skin", "Lil' Ghost", null, 'Spooky', 'Common', 16, false, 'chars8x8rPets1'],
  32818: ['Spirit Skin', 'Spirit', 2, 'Spooky', 'Common', 101, false, 'chars8x8rPets1'],
  32819: ['Baby Skin', 'Baby', null, 'Humanoid', 'Common', 45, false, 'chars8x8rPets1'],
  32821: ['Dreidel Skin', 'Dreidel', null, '? ? ? ?', 'Common', 67, false, 'chars8x8rPets1'],
  32822: ['Sprite Star Skin', 'Sprite Star', 2, '? ? ? ?', 'Common', 102, false, 'chars8x8rPets1'],
  32823: ['Blue Thing Skin', 'Blue Thing', null, '? ? ? ?', 'Common', 77, false, 'chars8x8rPets1'],
  32824: ['Robobuddy Skin', 'Robobuddy', null, 'Automaton', 'Common', 51, false, 'chars8x8rPets1'],
  32825: ['Helmbot Skin', 'Helmbot', null, 'Automaton', 'Common', 78, false, 'chars8x8rPets1'],
  32826: ['Lion Skin', 'Lion', null, 'Feline', 'Rare', 8, false, 'chars8x8rPets1'],
  32827: ['White Lion Skin', 'White Lion', null, 'Feline', 'Rare', 88, false, 'chars8x8rPets1'],
  32828: ['Ninja Cat Skin', 'Ninja Cat', null, 'Feline', 'Rare', 65, false, 'chars8x8rPets1'],
  32829: [
    'Golden Sheepdog Skin',
    'G. Sheepdog',
    null,
    'Canine',
    'Rare',
    99,
    false,
    'chars8x8rPets1'
  ],
  32830: ['Black Wolf Skin', 'Black Wolf', null, 'Canine', 'Rare', 100, false, 'chars8x8rPets1'],
  32831: ['Gold Bulldog Skin', 'Gold Bulldog', null, 'Canine', 'Rare', 79, false, 'chars8x8rPets1'],
  32832: ['Eagle Skin', 'Eagle', null, 'Avian', 'Rare', 23, false, 'chars8x8rPets1'],
  32833: ['Raven Skin', 'Raven', null, 'Avian', 'Rare', 28, false, 'chars8x8rPets1'],
  32834: ['USA Eagle Skin', 'USA Eagle', 1, 'Avian', 'Rare', 71, false, 'chars8x8rPets1'],
  32835: ['Pigeon Skin', 'Pigeon', null, 'Avian', 'Rare', 80, false, 'chars8x8rPets1'],
  32836: ['Panda Skin', 'Panda', null, 'Exotic', 'Rare', 11, false, 'chars8x8rPets1'],
  32837: ['Toucan Skin', 'Toucan', null, 'Exotic', 'Rare', 19, false, 'chars8x8rPets1'],
  32838: ['Orangutan Skin', 'Orangutan', null, 'Exotic', 'Rare', 81, false, 'chars8x8rPets1'],
  32839: ['Mallard Skin', 'Mallard', null, 'Farm', 'Rare', 21, false, 'chars8x8rPets1'],
  32840: ['Turkey Skin', 'Turkey', 2, 'Farm', 'Rare', 44, false, 'chars8x8rPets1'],
  32841: ['Skunk Skin', 'Skunk', null, 'Woodland', 'Rare', 20, false, 'chars8x8rPets1'],
  32842: ['Snowy Owl Skin', 'Snowy Owl', null, 'Woodland', 'Rare', 43, false, 'chars8x8rPets1'],
  32843: ['Reindeer Skin', 'Reindeer', null, 'Woodland', 'Rare', 68, false, 'chars8x8rPets1'],
  32844: ['Baby Dragon Skin', 'Baby Dragon', null, 'Reptile', 'Rare', 46, false, 'chars8x8rPets1'],
  32846: ['Bee Skin', 'Bee', null, 'Insect', 'Rare', 26, false, 'chars8x8rPets1'],
  32847: ['Praying Mantis Skin', 'Mantis', null, 'Insect', 'Rare', 66, false, 'chars8x8rPets1'],
  32848: ['Karate Red Skin', 'Karate R.', null, 'Penguin', 'Rare', 47, false, 'chars8x8rPets1'],
  32849: ['Karate Blue Skin', 'Karate B.', null, 'Penguin', 'Rare', 48, false, 'chars8x8rPets1'],
  32850: ['Karate Yellow Skin', 'Karate Y.', null, 'Penguin', 'Rare', 49, false, 'chars8x8rPets1'],
  32851: ['Karate Purple Skin', 'Karate P.', null, 'Penguin', 'Rare', 50, false, 'chars8x8rPets1'],
  32852: ['Demon Frog Skin', 'Demon Frog', 2, 'Aquatic', 'Rare', 36, false, 'chars8x8rPets1'],
  32853: [
    'Peppermint Snail Skin',
    'Candy Snail',
    null,
    'Aquatic',
    'Rare',
    58,
    false,
    'chars8x8rPets1'
  ],
  32854: ['Gargoyle Skin', 'Gargoyle', null, 'Spooky', 'Rare', 37, false, 'chars8x8rPets1'],
  32855: ["Lil' Cyclops Skin", "Lil' Cyclops", null, 'Spooky', 'Rare', 41, false, 'chars8x8rPets1'],
  32856: ['Werewolf Cub Skin', 'Werewolf', 2, 'Spooky', 'Rare', 63, false, 'chars8x8rPets1'],
  32857: ['Monster Eye Skin', 'Monster Eye', null, 'Spooky', 'Rare', 82, false, 'chars8x8rPets1'],
  32858: ['Skull Skin', 'Skull', null, 'Spooky', 'Rare', 83, false, 'chars8x8rPets1'],
  32859: ['Leprechaun Skin', 'Leprechaun', null, 'Humanoid', 'Rare', 17, false, 'chars8x8rPets1'],
  32860: ['Elf Skin', 'Elf', null, 'Humanoid', 'Rare', 31, false, 'chars8x8rPets1'],
  32861: ['Mermaid Skin', 'Mermaid', null, 'Humanoid', 'Rare', 84, false, 'chars8x8rPets1'],
  32862: ['Jelly Skin', 'Jelly', null, '? ? ? ?', 'Rare', 25, false, 'chars8x8rPets1'],
  32863: ['Gummy Bear Skin', 'Gummy Bear', null, '? ? ? ?', 'Rare', 38, false, 'chars8x8rPets1'],
  32864: ['Snowman Skin', 'Snowman', null, '? ? ? ?', 'Rare', 52, false, 'chars8x8rPets1'],
  32865: ['Jalapeno Skin', 'Jalapeno', null, '? ? ? ?', 'Rare', 85, false, 'chars8x8rPets1'],
  32866: ['Redbot Skin', 'Redbot', null, 'Automaton', 'Rare', 86, false, 'chars8x8rPets1'],
  32867: ['Funkatron Skin', 'Funkatron', null, 'Automaton', 'Rare', 87, false, 'chars8x8rPets1'],
  32868: ['Tiger Skin', 'Great Tiger', null, 'Feline', 'Divine', 0, false, 'petsDivine'],
  32869: ['Pink Lion Skin', 'Pink Lion', null, 'Feline', 'Divine', 1, false, 'petsDivine'],
  32870: ['Midnight Wolf Skin', 'Shadow Wolf', 3, 'Canine', 'Divine', 2, false, 'petsDivine'],
  32871: ['Golden Hyena Skin', 'Golden Hyena', null, 'Canine', 'Divine', 3, false, 'petsDivine'],
  32872: ['Phoenix Skin', 'Phoenix', null, 'Avian', 'Divine', 4, false, 'petsDivine'],
  32873: ['Griffin Skin', 'Griffin', null, 'Avian', 'Divine', 5, false, 'petsDivine'],
  32874: ['War Elephant Skin', 'War Elephant', null, 'Exotic', 'Divine', 6, false, 'petsDivine'],
  32875: ['King Gorilla Skin', 'King Gorilla', null, 'Exotic', 'Divine', 7, false, 'petsDivine'],
  32876: ['Enraged Yack Skin', 'Enraged Yak', null, 'Farm', 'Divine', 8, false, 'petsDivine'],
  32877: ['Night Mare Skin', 'Night Mare', null, 'Farm', 'Divine', 9, false, 'petsDivine'],
  32878: ['Silver Doe Skin', 'Silver Doe', null, 'Woodland', 'Divine', 10, false, 'petsDivine'],
  32879: ['Solar Owl Skin', 'Solar Owl', null, 'Woodland', 'Divine', 11, false, 'petsDivine'],
  32880: ['Tandem Cobra Skin', 'Tandem Cobra', null, 'Reptile', 'Divine', 12, false, 'petsDivine'],
  32881: ['Poison Drake Skin', 'Poison Drake', null, 'Reptile', 'Divine', 13, false, 'petsDivine'],
  32882: ['Beetleman Skin', 'Beetleman', null, 'Insect', 'Divine', 14, false, 'petsDivine'],
  32883: ['Ultrawasp Skin', 'Ultrawasp', null, 'Insect', 'Divine', 15, false, 'petsDivine'],
  32884: ['Battle Penguin Skin', 'Battle P.', null, 'Penguin', 'Divine', 16, false, 'petsDivine'],
  32885: ['Tank Penguin Skin', 'Tank Penguin', null, 'Penguin', 'Divine', 17, false, 'petsDivine'],
  32886: ['Golden Crab Skin', 'Golden Crab', null, 'Aquatic', 'Divine', 18, false, 'petsDivine'],
  32887: ['Great Shark Skin', 'Great Shark', null, 'Aquatic', 'Divine', 19, false, 'petsDivine'],
  32888: [
    'Blue Landfish Skin',
    'Blue Landfish',
    null,
    'Aquatic',
    'Divine',
    20,
    false,
    'petsDivine'
  ],
  32889: ['Glowing Skull Skin', 'Glowing Skull', null, 'Spooky', 'Divine', 21, false, 'petsDivine'],
  32890: ['Monkey Head Skin', 'Monkey Head', null, 'Spooky', 'Divine', 22, false, 'petsDivine'],
  32891: ['Reaper Skin', 'Reaper', null, 'Spooky', 'Divine', 23, false, 'petsDivine'],
  32892: ['Battle God Skin', 'Battle God', null, 'Humanoid', 'Divine', 24, false, 'petsDivine'],
  32893: ['Centaur Skin', 'Centaur', null, 'Humanoid', 'Divine', 25, false, 'petsDivine'],
  32894: ['Forest Fairy Skin', 'Forest Fairy', null, 'Humanoid', 'Divine', 26, false, 'petsDivine'],
  32895: ['Shroom Skin', 'Shroom', null, '? ? ? ?', 'Divine', 27, false, 'petsDivine'],
  32896: ['Great Jelly Skin', 'Great Jelly', null, '? ? ? ?', 'Divine', 28, false, 'petsDivine'],
  32897: ['Spiderbot Skin', 'Spiderbot', null, 'Automaton', 'Divine', 29, false, 'petsDivine'],
  32898: ['Cylindron Skin', 'Cylindron', null, 'Automaton', 'Divine', 30, false, 'petsDivine'],
  32899: ['Gutsbot Skin', 'Gutsbot', null, 'Automaton', 'Divine', 31, false, 'petsDivine'],
  32900: [
    "Lil' Oryx Skin",
    "Lil' Oryx",
    null,
    '? ? ? ?',
    'Divine',
    36,
    true,
    'chars16x16dEncounters2'
  ],
  32912: ['Disabled Pet Skin', 'Disabled Pet', null, null, null, 0, false, 'chars8x8rPets2'],
  34607: [
    'Chibi Oryx Gladiator Pet Skin',
    'Chibi Oryx Gladiator',
    4,
    'Humanoid',
    'Divine',
    254,
    false,
    'petsDivine'
  ],
  34610: [
    'Crucible Pet Rock Skin',
    'Pet Rock',
    null,
    '? ? ? ?',
    'Divine',
    255,
    false,
    'petsDivine'
  ],
  34803: [
    'Sturdy Beer Barrel Pet Skin',
    'Sturdy Beer Barrel',
    4,
    '? ? ? ?',
    'Divine',
    257,
    false,
    'petsDivine'
  ],
  34806: ['Wolpertinger Pet Skin', 'Wolpertinger', 4, 'Farm', 'Divine', 258, false, 'petsDivine'],
  34809: ['Happy Dog Pet Skin', 'Happy Dog', 4, 'Canine', 'Divine', 259, false, 'petsDivine'],
  35078: ['Kelpie Pet Skin', 'Kelpie', 3, 'Aquatic', 'Divine', 260, false, 'petsDivine'],
  35081: ['Hydra Pet Skin', 'Hydra', 4, 'Reptile', 'Divine', 261, false, 'petsDivine'],
  35084: [
    'Ancient Gryphon Pet Skin',
    'Ancient Gryphon',
    4,
    'Avian',
    'Divine',
    262,
    false,
    'petsDivine'
  ],
  35087: [
    'Ancient Chimera Pet Skin',
    'Ancient Chimera',
    4,
    'Feline',
    'Divine',
    263,
    false,
    'petsDivine'
  ],
  35090: [
    'Ancient Pegasus Pet Skin',
    'Ancient Pegasus',
    4,
    'Farm',
    'Divine',
    264,
    false,
    'petsDivine'
  ],
  35093: [
    'Gingerbread Golem Pet Skin',
    'Gingerbread Golem',
    4,
    '? ? ? ?',
    'Divine',
    265,
    false,
    'petsDivine'
  ],
  35096: [
    'Fluffy Snowy Owl Pet Skin',
    'Fluffy Snowy Owl',
    4,
    'Avian',
    'Divine',
    266,
    false,
    'petsDivine'
  ],
  35099: [
    'Little Helper Bot Pet Skin',
    'Little Helper Bot',
    4,
    'Automaton',
    'Divine',
    267,
    false,
    'petsDivine'
  ],
  35102: [
    'Oryxmas Tree Pet Skin',
    'Oryxmas Tree',
    5,
    'Woodland',
    'Divine',
    268,
    false,
    'petsDivine'
  ],
  35105: ['Strange Bunny Pet Skin', 'Strange Bunny', 4, 'Farm', 'Divine', 269, false, 'petsDivine'],
  35108: ['Quasar Pup Pet Skin', 'Quasar Pup', 4, 'Canine', 'Divine', 270, false, 'petsDivine'],
  35111: [
    'Caged Prisoner Pet Skin',
    'Caged Prisoner',
    4,
    'Spooky',
    'Divine',
    277,
    false,
    'petsDivine'
  ],
  35114: [
    'Zodiac Dragon Pet Skin',
    'Zodiac Dragon',
    null,
    'Reptile',
    'Divine',
    271,
    false,
    'petsDivine'
  ],
  35117: [
    'Baby Blue Dragon Skin',
    'Baby Blue Dragon',
    4,
    'Reptile',
    'Divine',
    272,
    false,
    'petsDivine'
  ],
  35120: ['Harpist Demon Skin', 'Harpist Demon', 3, 'Humanoid', 'Divine', 273, false, 'petsDivine'],
  35123: ['Chaos Dragon Skin', 'Chaos Dragon', 4, 'Reptile', 'Divine', 274, false, 'petsDivine'],
  35126: ['Mini Pyyr Skin', 'Mini Pyyr', 3, 'Reptile', 'Divine', 275, false, 'petsDivine'],
  35129: [
    'Penguin Cupid Pet Skin',
    'Penguin Cupid',
    3,
    'Penguin',
    'Divine',
    276,
    false,
    'petsDivine'
  ],
  35234: ['Marid Skin', 'Marid', null, 'Humanoid', 'Divine', 32, false, 'petsDivine'],
  50287: [
    'Toy Bot K.B Pet Skin',
    'Toy Bot K.B',
    4,
    'Automaton',
    'Divine',
    239,
    false,
    'petsDivine'
  ],
  50290: [
    'Kogbold Maid Pet Skin',
    'Kogbold Maid',
    4,
    'Reptile',
    'Divine',
    238,
    false,
    'petsDivine'
  ],
  50699: [
    'Zodiac Bunny Pet Skin',
    'Zodiac Bunny',
    null,
    'Farm',
    'Divine',
    240,
    false,
    'petsDivine'
  ],
  50702: ['Model K999 Pet Skin', 'Model K999', 4, 'Canine', 'Divine', 241, false, 'petsDivine'],
  50705: [
    'Gentle Unicorn Pet Skin',
    'Gentle Unicorn',
    2,
    'Farm',
    'Divine',
    242,
    false,
    'petsDivine'
  ],
  50708: ['Genie Lamp Pet Skin', 'Genie Lamp', 4, 'Humanoid', 'Divine', 243, false, 'petsDivine'],
  50711: [
    'Flying Carpet Pet Skin',
    'Flying Carpet',
    2,
    'Spooky',
    'Divine',
    244,
    false,
    'petsDivine'
  ],
  50714: ['King Cobra Pet Skin', 'King Cobra', 4, 'Reptile', 'Divine', 245, false, 'petsDivine'],
  50717: [
    'Chibi Kitsune Umi Pet Skin',
    'Chibi Kitsune Umi',
    5,
    'Humanoid',
    'Divine',
    246,
    false,
    'petsDivine'
  ],
  50720: [
    'Abyssal Crab Pet Skin',
    'Abyssal Crab',
    3,
    'Aquatic',
    'Divine',
    247,
    false,
    'petsDivine'
  ],
  50723: ['Cryophoenix Pet Skin', 'Cryophoenix', 4, 'Avian', 'Divine', 248, false, 'petsDivine'],
  50726: [
    'Spectral Raven Pet Skin',
    'Spectral Raven',
    4,
    'Avian',
    'Divine',
    249,
    false,
    'petsDivine'
  ],
  50729: ['Void Child Pet Skin', 'Void Child', 4, 'Humanoid', 'Divine', 250, false, 'petsDivine'],
  50732: [
    'Gelatinous Warrior Pet Skin',
    'Gelatinous Warrior',
    3,
    '? ? ? ?',
    'Divine',
    251,
    false,
    'petsDivine'
  ],
  50735: ['Karate Pug Pet Skin', 'Karate Pug', 4, 'Canine', 'Divine', 252, false, 'petsDivine'],
  50738: [
    'Echo of a Hero Pet Skin',
    'Echo of a Hero',
    5,
    'Humanoid',
    'Divine',
    253,
    false,
    'petsDivine'
  ],
  51290: [
    'Chibi Leprechaun Pet Skin',
    'Chibi Leprechaun',
    4,
    'Humanoid',
    'Divine',
    278,
    false,
    'petsDivine'
  ],
  51293: [
    'Wondrous Basket Pet Skin',
    'Wondrous Basket',
    4,
    'Farm',
    'Divine',
    279,
    false,
    'petsDivine'
  ],
  51296: [
    'Eggstravagant Egg Pet Skin',
    'Eggstravagant Egg',
    4,
    'Farm',
    'Divine',
    280,
    false,
    'petsDivine'
  ],
  51299: [
    "Biff's Best Friend Pet Skin",
    "Biff's Best Friend",
    4,
    'Canine',
    'Divine',
    281,
    false,
    'petsDivine'
  ],
  51302: [
    "Manager's Best Friend Alice Pet Skin",
    "Manager's Best Friend Alice",
    null,
    'Canine',
    'Divine',
    282,
    false,
    'petsDivine'
  ],
  51339: ['Cracked Egg Pet Skin', 'Cracked Egg', 5, 'Exotic', 'Divine', 283, false, 'petsDivine'],
  51427: [
    'Nile Crocodile Pet Skin',
    'Nile Crocodile',
    4,
    'Reptile',
    'Divine',
    284,
    false,
    'petsDivine'
  ],
  51430: [
    'Chibi Penguin Mummy Pet Skin',
    'Chibi Penguin Mummy',
    4,
    'Penguin',
    'Divine',
    285,
    false,
    'petsDivine'
  ],
  51433: [
    'Sphinx Guardian Pet Skin',
    'Sphinx Guardian',
    4,
    'Humanoid',
    'Divine',
    286,
    false,
    'petsDivine'
  ],
  51490: [
    'Red Hot Scarab Pet Skin',
    'Red Hot Scarab',
    4,
    'Insect',
    'Divine',
    287,
    false,
    'petsDivine'
  ],
  51495: [
    'Sunflower Scarab Pet Skin',
    'Sunflower Scarab',
    4,
    'Insect',
    'Divine',
    288,
    false,
    'petsDivine'
  ],
  51552: [
    'Chibi Avatar of the Forgotten King Pet Skin',
    'Chibi Avatar of the Forgotten King',
    4,
    'Spooky',
    'Divine',
    289,
    false,
    'petsDivine'
  ],
  51555: [
    'Chibi Avatar of the Accursed King Pet Skin',
    'Chibi Avatar of the Accursed King',
    4,
    'Spooky',
    'Divine',
    290,
    false,
    'petsDivine'
  ],
  51562: [
    'Deep Sea Companion Pet Skin',
    'Deep Sea Companion',
    4,
    'Aquatic',
    'Divine',
    291,
    false,
    'petsDivine'
  ],
  51565: [
    'Mushroom Buddy Pet Skin',
    'Mushroom Buddy',
    4,
    'Woodland',
    'Divine',
    292,
    false,
    'petsDivine'
  ],
  51668: ['Hermit Crab Pet Skin', 'Hermit Crab', 4, 'Aquatic', 'Divine', 293, false, 'petsDivine'],
  51720: [
    'the Void Star Pet Skin',
    'the Void Star',
    3,
    '? ? ? ?',
    'Divine',
    294,
    false,
    'petsDivine'
  ]
};
